### PR TITLE
Fixed vehicle ground status and position.

### LINKED ISSUE #5537: Flying Boat during crossplay
### Describe the bug

So me and my friend were playing minecraft.I am on Java and she is on bedrock(on a phone) and whenever she gets in the boat she somehow "lifts"out of the water.When i am driving the boat it works normally but whenever its just her then it sort of lifts up

### To Reproduce

1.get on a boat and it will start floating

### Expected behaviour

it should look like this 

Image

### Screenshots / Videos

When she is riding the boat it lifts her up

Image
Image

### Server Version and Plugins

version is 1.21.5

### Geyser Dump

_No response_

### Geyser Version

825 (Bedrock v1.21.50 - v1.21.80) -(this is copypasted from aternos)

### Minecraft: Bedrock Edition Device/Version

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Oryxel**
Should fix #5537 and also the ground status should now be more accurate.

### CODE REVIEW

File: core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/input/BedrockPlayerAuthInputTranslator.java [hunk 1]
```diff
@@ -324,8 +324,7 @@ private static void processVehicleInput(GeyserSession session, PlayerAuthInputPa
         }
 
         if (sendMovement) {
-            // Can't rely on y-delta being 0, as the value is -0.078 even when standing still
-            vehicle.setOnGround(Math.abs(packet.getDelta().getY()) < 0.1);
+            vehicle.setOnGround(packet.getInputData().contains(PlayerAuthInputData.VERTICAL_COLLISION) && session.getPlayerEntity().getLastTickEndVelocity().getY() < 0);
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/input/BedrockPlayerAuthInputTranslator.java:327]: Can you test whether this also works correctly while riding horses?

Comment (Oryxel) [reply core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/input/BedrockPlayerAuthInputTranslator.java:327]: Yep, seems to be working fine.

**Review by onebeastchris — APPROVED** [review]
thanks!
