### PR TITLE
Some fixes related to flags.

### LINKED ISSUE #5316: Even if you are crawling, Bedrock will show you as swimming.
### Describe the bug

Although the crawl was added to BedrockEdition around 1.20.30, GeyserMC still converts the crawl into a swimming state and displays the crawl.

### To Reproduce

See the player in crawl state in BedrockEdition

### Expected behaviour

Use the crawl implemented in BedrockEdition

### Screenshots / Videos

Image
Image

### Server Version and Plugins

This server is running Paper version 1.21.4-136-main@e0711af (2025-01-31T12:30:12Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.3-82-5a60ffb (MC: 1.21.3)

Paper Plugins:
 - PrefiX
Bukkit Plugins:
 - AdvancedPortals, AdvancedReplay, AntiCheatReplay, *AntiSpam, BungeeGuard, CommandPanels, CoreProtect, floodgate, GeyserSkinManager, GrapplingHook
  GrimAC, GSit, JukeBox, LightAntiCheat, LuckPerms, *LunaChat, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, NoteBlockAPI
  NoteBlockMusicPlayer, OldCombatMechanics, OpenInv, ProtocolLib, Shieldfix, Skywars, TAB, TNTRun, ViaBackwards, ViaRewind
  ViaRewind-Legacy-Support, ViaVersion, voicechat, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/cu7cYsx5ND4O9ZMb3hKPFZqaoxQFXPZT

### Geyser Version

2.6.0-SNAPSHOT (git-DEV-946617c)

### Minecraft: Bedrock Edition Device/Version

1.21.51 (Windows11 24h2)

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by oryxel1**
Changes:
- Sending PUSH_TOWARDS_CLOSEST_SPACE to session player so the behaviour is now more Java like when you're "stuck" inside a block and can easily enter for ex: crawl mode using a trapdoor more easily.
- Added COLLIDABLE for shulker and also allow shulker to be visible when it's invisible (again) so https://github.com/GeyserMC/GeyserOptionalPack/ shulker invisibility parity trick works again.
- Now send pitch 0 if you're crawling, resolve #5316, but this will only fix it for other player, not the session itself, and it's a "hack".

### CODE REVIEW

File: core/src/main/java/org/geysermc/geyser/entity/type/player/PlayerEntity.java [hunk 1]
```diff
@@ -422,6 +423,32 @@ protected void scoreVisibility(boolean show) {
...
+                setFlag(EntityFlag.SWIMMING, true);
+            } else {
+                setFlag(EntityFlag.CRAWLING, true);
+            }
+        }
+
+        // Look at https://github.com/GeyserMC/Geyser/issues/5316, we're fixing this by spoofing player pitch to 0.
+        if (getFlag(EntityFlag.CRAWLING)) {
+            updateRotation(this.yaw, 0, this.onGround);
+        }
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/entity/type/player/PlayerEntity.java]: This could probably be moved up into the if-statement above, as the crawling flag is false anyways since that was reset at the top

**Review by onebeastchris — CHANGES_REQUESTED** [review]

**Review by onebeastchris — APPROVED** [review]
Thanks! Looks good to me :)
