### PR TITLE
Fix: Allow players to hit air

### LINKED ISSUE #5190: Bedrock mobile (touch screen) can't punch air with new UI
### Describe the bug

The new bedrock UI for mobile stops the player from punching the air when in a server that uses Geyser. From testing, they can only punch blocks and near by players/mobs.

### To Reproduce

1. Open minecraft on a mobile device
2. Join a server that uses Geyser
3. Try to punch the air

### Expected behaviour

Nothing will happen.

### Screenshots / Videos

https://github.com/user-attachments/assets/851b3737-0c06-4e36-ab72-37125ddedd0d

Video of a player in the Megacrafting server showing the bug.

### Server Version and Plugins

I'm a player on the server so I'm unsure of the plugins.

### Geyser Dump

_No response_

### Geyser Version

Latest

### Minecraft: Bedrock Edition Device/Version

1.21.50

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by onebeastchris**
Should fix https://github.com/GeyserMC/Geyser/issues/5190

Further, this implements blocking block breaking & entity attacking while steering boats to match the Java clients behaviour.

It now also updates shifting state before sending inputs to the Java client, also matching behaviour there.

### CODE REVIEW

File: core/src/main/java/org/geysermc/geyser/session/GeyserSession.java [hunk 1]
```diff
@@ -1642,6 +1643,9 @@ public void sendUpstreamPacketImmediately(BedrockPacket packet) {
      * @param packet the java edition packet from MCProtocolLib
      */
     public void sendDownstreamGamePacket(Packet packet) {
+        if (packet instanceof ServerboundSwingPacket) {
+            geyser.getLogger().error("sending: " + packet.toString());
```
Comment (rtm516) [inline core/src/main/java/org/geysermc/geyser/session/GeyserSession.java:1647]: Is this meant to be here still?

Comment (onebeastchris) [reply core/src/main/java/org/geysermc/geyser/session/GeyserSession.java:1647]: will remove before merge, this could use some testing on other platforms

File: core/src/main/java/org/geysermc/geyser/dump/DumpInfo.java [hunk 2]
```diff
@@ -87,7 +87,7 @@ public DumpInfo(GeyserImpl geyser, boolean addLog) {
         this.cpuCount = Runtime.getRuntime().availableProcessors();
         this.cpuName = CpuUtils.tryGetProcessorName();
         this.systemLocale = Locale.getDefault();
-        this.systemEncoding = System.getProperty("file.encoding");
+        this.systemEncoding = System. getProperty("file.encoding");
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/dump/DumpInfo.java:90]:
```suggestion
        this.systemEncoding = System.getProperty("file.encoding");
```

File: core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/input/BedrockPlayerAuthInputTranslator.java [hunk 3]
```diff
@@ -154,7 +147,28 @@ public void translate(GeyserSession session, PlayerAuthInputPacket packet) {
                     sendPlayerGlideToggle(session, entity);
                 }
                 case STOP_GLIDING -> sendPlayerGlideToggle(session, entity);
-                case MISSED_SWING -> CooldownUtils.sendCooldown(session); // Java edition sends a cooldown when hitting air.
+                case MISSED_SWING -> {
+                    // mobile: animate after swing
+                    // win: swing after animate
+                    GeyserImpl.getInstance().getLogger().info("auth packet, tick: " + session.getTicks() + " " + packet.toString());
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/input/BedrockPlayerAuthInputTranslator.java:153]:
```suggestion
```

**Comment by gabe0700-ship-it** [comment]
> Should fix https://github.com/GeyserMC/Geyser/issues/5190
> 
> Further, this implements blocking block breaking & entity attacking while steering boats to match the Java clients behaviour.
> 
> It now also updates shifting state before sending inputs to the Java client, also matching behaviour there.

How to download

**Comment by Novampr** [comment]
This PR was already merged in, just get the latest version of Geyser.
