### PR TITLE
Fix mob mount positions

### LINKED ISSUE #1354: Mobs mount position error
**Describe the bug**
 
Mobs mount position error

**To Reproduce**

Screenshot_20200930_175707_com mojang minecraftpe
It's also a problem when mobs ride the Ravager

**Expected behavior**

The correct riding position should be displayed
**Screenshots / Videos**

**Server Version**

IMG20200930180443

**Geyser Version**

IMG20200930180503

**Minecraft: Bedrock Edition Version**

1.16.20

### PR DESCRIPTION
**Pull request by davchoo**
Fixes #1354 and other jockeys.

### CODE REVIEW

**Review by RednedEpic — APPROVED** [review]

File: connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntitySetPassengersTranslator.java [hunk 1]
```diff
@@ -99,66 +101,149 @@ public void translate(ServerEntitySetPassengersPacket packet, GeyserSession sess
...
+                    break;
+            }
+            /*
+             * Bedrock Differences
+             * Zoglin & Hoglin seem to be taller in Bedrock edition
+             * Horses are tinier
+             * Players, Minecarts, and Boats have different origins
+             */
+            if (passenger.getEntityType() == EntityType.PLAYER) {
+                yOffset += 1.6f;
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntitySetPassengersTranslator.java:233]: If this is specifically 1.62, maybe set this to `EntityType.PLAYER.getOffset()`?

**Review by DoctorMacc — COMMENTED** [review]
Thanks so much for the PR! Will be great to get this finally taken care of.

My only question is: is this all hardcoded in Java Edition as well? I was hoping there was some magical equation that determines what the height should be.

**Comment by davchoo** [comment]
For some entities there is a hardcoded height offset and a mounted height offset. Most use the defaults, 0 for the height offset and 0.75 * height for the mounted height offset.

File: connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntitySetPassengersTranslator.java [hunk 2]
```diff
@@ -99,66 +101,149 @@ public void translate(ServerEntitySetPassengersPacket packet, GeyserSession sess
...
+                this.updateOffset(passenger, entity, session, (packet.getPassengerIds()[0] == passengerId), true, (packet.getPassengerIds().length > 1));
             }
 
             // Force an update to the passenger metadata
             passenger.updateBedrockMetadata(session);
         }
-
-        if (entity.getEntityType() == EntityType.HORSE) {
-            entity.getMetadata().put(EntityData.RIDER_SEAT_POSITION, Vector3f.from(0.0f, 2.3200102f, -0.2f));
-            entity.getMetadata().put(EntityData.RIDER_MAX_ROTATION, 181.0f);
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntitySetPassengersTranslator.java:111]: Can you reimplement this? Without it, player rotation locking on horses is weird. 

Otherwise, I tested the PR; looks great.

Comment (davchoo) [reply connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntitySetPassengersTranslator.java:111]: I can't seem to find any difference with or without these lines, but I've re-added them.

Comment (DoctorMacc) [reply connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntitySetPassengersTranslator.java:111]: Hmm, OK. I'll try to do some final testing tonight and then merge this in.

**Comment by DoctorMacc** [comment]
Well, the problem is solved on my end.  Thanks for the PR!
