### PR TITLE
Fixed water bucket placing.

### LINKED ISSUE #5138: Bug on phone when placing buckets of water/lava etc.
### Describe the bug

Simply by trying to place a bucket it will not be placed in the place where it should, it only happens to players who use a phone

### To Reproduce

1. Connect from your mobile
2. Use the default Minecraft controls
3. Try placing buckets of water or lava, the same thing happens with all of them

### Expected behaviour

It should not be placed correctly,

### Screenshots / Videos

https://drive.google.com/file/d/1OfA5mGaCPbyRFzGGb5z2FsCgJXvDCGKS/view?usp=drivesdk

### Server Version and Plugins

>....[14:21:10 INFO]: Este servidor está ejecutando la versión Geyser 2.5.0-b711 (git-master-4598ffe) (Versión Java: 1.21.3, Versión Bedrock: 1.20.80/1.20.81 - 1.21.40 - 1.21.44)

### Geyser Dump

https://dump.geysermc.org/Mk9eSbridEZpPgYOF3WXouCvqmHVYKCc

### Geyser Version

2.5.0-b711 (git-master-4598ffe) 

### Minecraft: Bedrock Edition Device/Version

All versions, only on phone or players who play with touch on their phone 

### Additional Context

_No response_

### LINKED ISSUE #5588: Crosshair mode doesn't work
### Describe the bug

In bedrock, you can disable crosshair mode which basically means you can place a block wherever you tap on the screen (instead of where the crosshairs are facing). In geyser, this doesn't work and blocks still teleport to the center of your screen and place

### To Reproduce

1. Disable crosshair mode to place blocks wherever you tap
2. Try and use the feature

NOTE: The person reporting has specifically reported it happening for them placing water. If you can't replicate with any block, try water

### Expected behaviour

It should place where you tap

### Screenshots / Videos

_No response_

### Server Version and Plugins

_No response_

### Geyser Dump

https://dump.geysermc.org/j8DhGWryfGEFSgkqn48AHRj7YxVts6sT

### Geyser Version

2.7.1-b830 (git-master-472ed8c)

### Minecraft: Bedrock Edition Device/Version

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by oryxel1**
Should resolve #5588 and resolve #5138.

I already tested this on my touch device, but it would be cool if someone test it themselves.

### CODE REVIEW

**Comment by oryxel1** [comment]
However I'm not sure if we should send ServerboundUseItemOnPacket when we are already sending ServerboundUseItemPacket

File: core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockInventoryTransactionTranslator.java [hunk 1]
```diff
@@ -633,8 +639,9 @@ private boolean useItem(GeyserSession session, InventoryTransactionPacket packet
             }
         }
 
-        Vector3f target = packet.getBlockPosition().toFloat().add(packet.getClickPosition());
-        lookAt(session, target);
+        // As of 1.21.5, this is no longer a vanilla behaviour.
+        // Vector3f target = packet.getBlockPosition().toFloat().add(packet.getClickPosition());
+        // lookAt(session, target);
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockInventoryTransactionTranslator.java]: is the lookup method used anywhere if not here?

File: core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/input/BedrockMovePlayer.java [hunk 2]
```diff
@@ -49,6 +49,8 @@ static void translate(GeyserSession session, PlayerAuthInputPacket packet) {
         SessionPlayerEntity entity = session.getPlayerEntity();
         if (!session.isSpawned()) return;
 
+        entity.setBedrockInteractRotation(packet.getInteractRotation());
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/input/BedrockMovePlayer.java:54]: let's add a comment how this is used for the bucket placing thing

File: core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockInventoryTransactionTranslator.java [hunk 3]
```diff
@@ -295,32 +295,22 @@ public void translate(GeyserSession session, InventoryTransactionPacket packet)
                             }
                         }
 
-                        // Storing the block position allows inconsistencies in block place checking from post-1.19 - pre-1.20.5 to be resolved.
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockInventoryTransactionTranslator.java]: So uh, slight issue - Java sends use item on packets *before* sending useItem packets, that order can't change

For context: (MojMap client: Minecraft#startUseItem, the block hit result will first call useItemOn; and stop if that interaction was successful; otherwise it'll send a use item if possible)

**Comment by oryxel1** [comment]
Ready to be merge :).

**Comment by onebeastchris** [comment]
Looks good to me - although i could imagine that this might not work on older Java edition servers? Worst case we re-add that lookAt logic. Small nitpick - GeyserSession's lookBackScheduledFuture can be removed here

**Comment by oryxel1** [comment]
> Looks good to me - although i could imagine that this might not work on older Java edition servers? Worst case we re-add that lookAt logic.

Yes, sadly as of 1.21.7 the lookAt behaviour is non vanilla behavior and will trip anticheat real bad. Unless we got a way to check the actual server version or as a config setting  I'd argue that this is ok for mow

**Review by onebeastchris — APPROVED** [review]
Will approve & merge now, as this does resolve the issue. Thanks for looking into this!
