### PR TITLE
Fix bounding box for 1.19.40 after death + respawn

### LINKED ISSUE #3370: Bedrock players getting stuck/clipping in blocks
### Describe the bug

Bedrock players seem to glitch/clip into blocks randomly ever since the new 1.19.40 update.

### To Reproduce

Login
Run into a block awkwardly or fall onto a block
You clip/glitch against blocks randomly
(Watch videos included you'll see what I mean)

### Expected behaviour

No clipping/glitching into blocks

### Screenshots / Videos

https://youtu.be/vv7CCozIj4A
https://youtu.be/ydHGqrU6QaM
https://youtu.be/YipYp9-FGnc

### Server Version and Plugins

Version: git-Purpur-1732

Plugins:
https://gyazo.com/f05125e6da2c0c5dab4b7e9c5604d59c

### Geyser Dump

https://dump.geysermc.org/KZIv5STerniCcd3ciIR5lvTb410sqFwW

### Geyser Version

2.1.0-SNAPSHOT (git-master-e9b99b2)

### Minecraft: Bedrock Edition Device/Version

Multiple Platforms

### Additional Context

Running Geyser Standalone for Bedrock Proxy
Running ViaVersion on Velocity for Java Proxy

### PR DESCRIPTION
**Pull request by Konicai**
Thanks to chris for looking into the differences in `SetEntityDataPacket` for BDS vs Geyser: https://paste.gg/p/anonymous/c9d62e15f69149e2973aa19c209ef0d4

This fixes the issue where 1.19.40 players are generally glitchy around anything that isn't flat ground.

Fixes #3370

### CODE REVIEW

File: core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockActionTranslator.java [hunk 1]
```diff
@@ -75,6 +75,10 @@ public void translate(GeyserSession session, PlayerActionPacket packet) {
                 attributesPacket.setRuntimeEntityId(entity.getGeyserId());
                 attributesPacket.getAttributes().addAll(entity.getAttributes().values());
                 session.sendUpstreamPacket(attributesPacket);
+
+                // Bounding box must be sent after a player dies and respawns since 1.19.40
+                entity.refreshBoundingBox();
+                entity.updateBedrockMetadata();
```
Comment (Camotoy) [inline core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockActionTranslator.java:81]: You can probably just call this in `refreshBoundingBox()` ?

Comment (Konicai) [reply core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockActionTranslator.java]: Thanks, didn't realize how often the entity data was sent

**Review by Camotoy — APPROVED** [review]
