### PR TITLE
Truncate problematic command descriptions

### LINKED ISSUE #6093: Long command descriptions prevent Bedrock clients from joining
### Describe the bug

Bedrock Edition 1.21.130 adds the following constraints on commands:

>   Chained Subcommand Data / Name max size set to 512 characters.
>   Commands / Name max size set to 512 characters.
>   Commands / Description max size set to 1000 characters.
>   Commands / Chained Subcommand Indexes max size set to 250 elements.
>   Commands / Overloads max size set to 250 elements.
>   Constraints / Constraint Indices max size set to 250 elements.

(Source: [Minecraft 1.21.130 Bedrock Changelog](https://www.minecraft.net/en-us/article/minecraft-1-21-130-bedrock-changelog))

Violating these constraints on the Java server results in the unhelpful client-side disconnect message "An error occurred" and a server-side "Disconnected" message when bedrock clients attempt to join.

### To Reproduce

1. Use a plugin to register a command with a description longer than 1000 characters
2. Attempt to join the server with a Bedrock client

### Expected behaviour

Bedrock clients should be able to connect despite the long command descriptions, as such long descriptions would overflow the command suggestions screen and be lost regardless.

### Screenshots / Videos

Bedrock edition disconnect screen showing 'An error occurred'

### Server Version and Plugins

Paper version:
```
This server is running Paper version 1.21.11-88-main@8556cb4 (2026-01-05T09:39:44Z) (Implementing API version 1.21.11-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.11-72-cd445fd (MC: 1.21.11)
```

Plugins: 
```
ℹ Server Plugins (8):
Paper Plugins (1):
 - LEATplex
Bukkit Plugins (7):
 - Apollo-Bukkit, FastAsyncWorldEdit, floodgate, Geyser-Spigot, ProtocolLib, voicechat, Votifier
```

### Geyser Dump

https://dump.geysermc.org/N6wvraAeFB6aJQaoAOrYovzsb5JpacZz

### Geyser Version

2.9.2-b1017 (git-master-f0815a9)

### Minecraft: Bedrock Edition Device/Version

1.21.131, iPadOS 1.17.10 and Windows 11 (likely all versions and platforms after 1.21.130)

### Additional Context

The other constraints mentioned above could also cause issues, however, descriptions were the only issues experienced with my plugin.

### LINKED ISSUE #6094: Command descriptions containing line breaks render the command list illegible
### Describe the bug

Command descriptions with line breaks render on Bedrock Edition without adding spacing before the following commands are listed, resulting in overlapping text as seen in the attached screenshot.

### To Reproduce

1. Create a plugin which registers a command with line breaks in their description
2. Observe the command suggestion list on Bedrock Edition containing that command

### Expected behaviour

The command suggestion list should be legible

### Screenshots / Videos

Image

### Server Version and Plugins

Paper version:
```
This server is running Paper version 1.21.11-88-main@8556cb4 (2026-01-05T09:39:44Z) (Implementing API version 1.21.11-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.11-72-cd445fd (MC: 1.21.11)
```

Plugins: 
```
ℹ Server Plugins (8):
Paper Plugins (1):
 - LEATplex
Bukkit Plugins (7):
 - Apollo-Bukkit, FastAsyncWorldEdit, floodgate, Geyser-Spigot, ProtocolLib, voicechat, Votifier
```

### Geyser Dump

https://dump.geysermc.org/N6wvraAeFB6aJQaoAOrYovzsb5JpacZz

### Geyser Version

 2.9.2-b1017 (git-master-f0815a9)

### Minecraft: Bedrock Edition Device/Version

1.21.131, iPadOS 1.17.10

### Additional Context

This is an issue with how Bedrock Edition displays command descriptions, but will likely not be fixed by Mojang as it is only caused by third-party plugins/servers.

### PR DESCRIPTION
**Pull request by ookiegajwa**
Command descriptions are truncated after 950 characters to comply with length limits introduced in 1.21.130 (fixes #6093)
The official limit in Mojang's changelog is 1000 characters, however, during testing, some commands would cause clients to disconnect at varying description lengths between 985 and 996 characters. Due to the lack of descriptive error messages available on the client, I was unable to determine why this was happening. By adding a 50 character buffer, the issue seems to be resolved. Any testing advice on this matter would be appreciated.

Command descriptions are also truncated at the first line break to avoid overlapping text in the command suggestion list (fixes #6094)

### CODE REVIEW

File: core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaCommandsTranslator.java [hunk 1]
```diff
@@ -211,8 +211,20 @@ public void translate(GeyserSession session, ClientboundCommandsPacket packet) {
...
+            // Command suggestion list is illegible if a command description contains line breaks
+            String description = entry.getKey().description();
+            if (description.contains("\n")) {
+                description = description.substring(0, description.indexOf('\n'));
+            }
+
+            // The maximum description length is 1000 characters, but issues are still experienced at that length with some commands
+            // As such, truncate descriptions at 950 characters
+            if (description.length() > 950) {
+                description = description.substring(0, 950);
```
Comment (rtm516) [inline core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaCommandsTranslator.java]: We should probably add an elipsis here to prevent people logging issues saying the descriptions are cut off mid word

**Comment by onebeastchris** [comment]
Thanks for the PR! Do you have a link to the changelog where this was mentioned?

**Review by onebeastchris — APPROVED** [review]

**Comment by hasankayra04** [comment]
> Thanks for the PR! Do you have a link to the changelog where this was mentioned?

See https://github.com/GeyserMC/Geyser/issues/6093 for the changelog.

File: core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaCommandsTranslator.java [hunk 2]
```diff
@@ -211,8 +211,20 @@ public void translate(GeyserSession session, ClientboundCommandsPacket packet) {
             // Create a basic alias
             CommandEnumData aliases = new CommandEnumData(commandName + "Aliases", values, false);
 
+            // Command suggestion list is illegible if a command description contains line breaks
+            String description = entry.getKey().description();
+            if (description.contains("\n")) {
```
Comment (Camotoy) [inline core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaCommandsTranslator.java]: I believe we can replace this with a variable saved of `description.indexOf('\n')` and check if that variable is equal to -1, then reuse the value on the next lline.

**Comment by Camotoy** [comment]
Thanks for the PR! Yeah, if we can link that this change started in .130 for historical purposes in the code, that would be appreciated!

File: core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaCommandsTranslator.java (hunk 1 above)
Comment (ookiegajwa) [reply core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaCommandsTranslator.java]: The command suggestions list does not have any kind of line wrapping, so descriptions of this length would reasonably be off-screen, and the `/help` command will use the full server-side description regardless. However, an ellipsis would be useful in the edge case of a very high-resolution or wide screen, and as future-proofing in case Mojang adds line wrapping support. I will add that, thank you for noticing!

**Comment by ookiegajwa** [comment]
I have updated the PR incorporating the suggestions from the reviews and comments, thank you for the feedback :)

I see an error in the GitHub Action to build the pull request, the same error as on the latest commit to master - is that issue related to this change?

**Comment by onebeastchris** [comment]
Yeah builds are currently failing due to the repo of a few dependencies having an invalid certificate - that's unrelated to your changes :)

**Comment by hasankayra04** [comment]
No, the build failure isn’t your fault—it’s due to https://maven.architectury.dev/ having an expired SSL certificate. We’re hoping it gets resolved soon.
