### PR TITLE
Refactor the collision system, fixes issues where player position randomly get lifted up, various improvements to how collision fixes is handle.

### LINKED ISSUE #4955: Damage with flooded chests
### Describe the bug

I fall on a flooded chest and take damage

### To Reproduce

we fall (height is more than 3 blocks) onto a chest (flooded with water) and take damage

### Expected behaviour

I fall on a flooded chest and take no damage

### Screenshots / Videos

_No response_

### Server Version and Plugins

_No response_

### Geyser Dump

_No response_

### Geyser Version

Newest

### Minecraft: Bedrock Edition Device/Version

1.21.2 Redmi 9A

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by oryxel1**
Changes:
- Deleted grass path collision fix since as of 1.21.71, this block collision is the same as java edition.
- Deleted the logic for stepping in `correctPosition`, since this caused many issues (already discuss in Discord).
- Refactor code inside `correctPosition`, make it little bit more readable.
- `correctPosition` now no longer return true/false, as in the original code this method always return true.
- Now for collisions fixes like trapdoor/door/glass pane/iron bar. Properly calculate the distance we actually need to move player position by instead of just moving it by a certain value, as the player could actually just clip less than that value, causing the position get offset more than it needed to.
- Fixed chest collision by moving player position down, resolve: #3277 and resolve #4955

---------------
* Tested with NCP to ensure that these changes will remain the same functionality while improve it to not break player movement.

### CODE REVIEW

**Comment by oryxel1** [comment]
These 2 videos showing how this looks when player collide with glass pane before/after the change, before the change player movement look janky and weird, sometimes even teleport around, meanwhile after the change player move normally, indistinguishable from a normal java player.

https://github.com/user-attachments/assets/2ccedadb-4002-4567-a619-3562e5340753
https://github.com/user-attachments/assets/1786a8d3-6bca-4e4d-b0ed-8c779b5357c4

File: core/src/main/java/org/geysermc/geyser/level/physics/BoundingBox.java [hunk 1]
```diff
@@ -197,7 +238,8 @@ public double getIntersectionSize(BoundingBox otherBoundingBox, Direction side)
     @SneakyThrows(CloneNotSupportedException.class)
     @Override
     public BoundingBox clone() {
-        BoundingBox clone = (BoundingBox) super.clone();
+        super.clone();
```
Comment (Camotoy) [inline core/src/main/java/org/geysermc/geyser/level/physics/BoundingBox.java]: This doesn't look right at *all*. super.clone() should return a cloned object. Why are we just letting it run?

Comment (oryxel1) [reply core/src/main/java/org/geysermc/geyser/level/physics/BoundingBox.java]: oops, you didn't see that :D, fixed.

File: core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/input/BedrockPlayerAuthInputTranslator.java [hunk 2]
```diff
@@ -78,6 +78,7 @@ public void translate(GeyserSession session, PlayerAuthInputPacket packet) {
         SessionPlayerEntity entity = session.getPlayerEntity();
 
         session.setClientTicks(packet.getTick());
+        session.setInputData(packet.getInputData());
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/input/BedrockPlayerAuthInputTranslator.java]: let's just store vertical_collision on the session player entity instead; both to avoid storing unnecessary data and removing variables stored in geysersession

File: core/src/main/java/org/geysermc/geyser/translator/collision/BlockCollision.java [hunk 3]
```diff
@@ -61,87 +50,44 @@ protected BlockCollision(BoundingBox[] boxes) {
...
-                if (Math.abs(translateDistance) < pushAwayTolerance) {
-                    playerCollision.translate(0, translateDistance, 0);
-                }
+    public void correctPosition(GeyserSession session, int x, int y, int z, BoundingBox playerCollision) {
+        final double collisionExpansion = CollisionManager.COLLISION_TOLERANCE * 2;
+        // Make player collision slightly bigger to pick up on blocks that could cause problems with Passable
+        playerCollision.setSizeX(playerCollision.getSizeX() + collisionExpansion);
+        playerCollision.setSizeY(playerCollision.getSizeY() + collisionExpansion);
+        playerCollision.setSizeZ(playerCollision.getSizeZ() + collisionExpansion);
+
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/translator/collision/BlockCollision.java:60]: If this is needed, playerCollision.expand(collisionExpansion) would do the same thing; or could add a TODO to look at later

**Review by onebeastchris — APPROVED** [review]
LGTM, will do some testing though - glad to see you working on movement fixes :)

File: core/src/main/java/org/geysermc/geyser/session/GeyserSession.java [hunk 4]
```diff
@@ -70,6 +70,7 @@
 import org.cloudburstmc.protocol.bedrock.data.GameRuleData;
 import org.cloudburstmc.protocol.bedrock.data.GameType;
 import org.cloudburstmc.protocol.bedrock.data.LevelEvent;
+import org.cloudburstmc.protocol.bedrock.data.PlayerAuthInputData;
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/session/GeyserSession.java]:
```suggestion
```

File: core/src/main/java/org/geysermc/geyser/session/GeyserSession.java [hunk 5]
```diff
@@ -234,6 +235,7 @@
 import java.util.Arrays;
 import java.util.BitSet;
 import java.util.Collections;
+import java.util.EnumSet;
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/session/GeyserSession.java]:
```suggestion
```

File: core/src/main/java/org/geysermc/geyser/level/physics/BoundingBox.java [hunk 6]
```diff
@@ -142,6 +142,47 @@ private boolean checkOverlapInAxis(double xOffset, double yOffset, double zOffse
         };
     }
 
+    public void pushOutOfBoundingBox(BoundingBox playerBox, Direction direction, double maxPushTolerance) {
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/level/physics/BoundingBox.java:145]: Is there a specific reason we're not pushing the player at all if it's at or higher as opposed to pushing the player by the max push distance distance?

File: core/src/main/java/org/geysermc/geyser/translator/collision/BlockCollision.java [hunk 7]
```diff
@@ -61,87 +50,40 @@ protected BlockCollision(BoundingBox[] boxes) {
...
-
-                double bottomFaceYPos = b.getMiddleY() - (b.getSizeY() / 2);
-                translateDistance = bottomFaceYPos - relativePlayerPosition.getY() - (playerCollision.getSizeY() / 2);
-                if (Math.abs(translateDistance) < pushAwayTolerance) {
-                    playerCollision.translate(0, translateDistance, 0);
-                }
+    public void correctPosition(GeyserSession session, int x, int y, int z, BoundingBox playerCollision) {
+        final double collisionExpansion = CollisionManager.COLLISION_TOLERANCE * 2;
+        // Make player collision slightly bigger to pick up on blocks that could cause problems with Passable
+        playerCollision.expand(collisionExpansion);
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/translator/collision/BlockCollision.java]: it this is outdated / something that should be looked at again (or this method generally), please add a TODO

**Review by onebeastchris — APPROVED** [review]
LGTM after these

File: core/src/main/java/org/geysermc/geyser/level/physics/BoundingBox.java (hunk 6 above)
Comment (oryxel1) [reply core/src/main/java/org/geysermc/geyser/level/physics/BoundingBox.java:145]: uhh complicated, we just shouldn't.
