### PR TITLE
Check if `items` of campfire block entity is null

### LINKED ISSUE #3985: Unable to render chunks with campfires
### Describe the bug

Having campfires/soul campfires (both lit and unlit) results in `[geyser]: Could not translate packet ClientboundLevelChunkWithLightPacket`

### To Reproduce

1. Set up a MineStom server
2. Make a map with both lit and unlit campfires
3. Load the MineStom server and have Velocity as a frontend
4. Observe the CampfireBlockEntityTranslator issue.

### Expected behaviour

World should load with no errors

### Screenshots / Videos

image
Left = Java
Right = Bedrock

image
More chunks with campfires are unable to load.

### Server Version and Plugins

MineStom implementation
> velocity plugins
[20:02:49 INFO]: Plugins: duck-velocity, floodgate, geyser, viaversion, viabackwards

Note: duck-velocity is a plugin to handle Discord messaging via an API, it does not touch floodgate or GeyserMC

### Geyser Dump

https://dump.geysermc.org/KrV1nV1W8IgHghRtXWeK0NDVsvvEWDuX

### Velocity Logs
https://mclo.gs/cfn5ptg

### Geyser Version

2.1.2-SNAPSHOT (git-master-c1d8009) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.10)

### Minecraft: Bedrock Edition Device/Version

1.20.1 Win 10 Edition

### Additional Context

WorldEditing all my Campfires resolved the issue.
Entities / particles still seem to load. However client cannot use wasd

### PR DESCRIPTION
**Pull request by Konicai**
Closes #3985

### CODE REVIEW

File: core/src/main/java/org/geysermc/geyser/translator/level/block/entity/CampfireBlockEntityTranslator.java [hunk 1]
```diff
@@ -40,10 +40,12 @@ public class CampfireBlockEntityTranslator extends BlockEntityTranslator {
     @Override
     public void translateTag(NbtMapBuilder builder, CompoundTag tag, int blockState) {
         ListTag items = tag.get("Items");
-        int i = 1;
-        for (Tag itemTag : items.getValue()) {
-            builder.put("Item" + i, getItem((CompoundTag) itemTag));
-            i++;
+        if (items != null) {
```
Comment (Camotoy) [inline core/src/main/java/org/geysermc/geyser/translator/level/block/entity/CampfireBlockEntityTranslator.java:43]: Take this line and the line above for `if (tag.get("Items") instanceof ListTag items)`?

**Review by Camotoy — APPROVED** [review]
