### PR TITLE
Translate nbt of decorated pots

### LINKED ISSUE #3843: Decorated pot designs aren't translated
### Describe the bug

The designs on decorated pots are not translated on bedrock, all pots are just blank.

### To Reproduce

1. Place down a pot with sherds on it in a geyser server
2. View the pot from a bedrock client. Notice how the design is not visible when placed or even in the inventory

### Expected behaviour

Bedrock players should see pot designs.

### Screenshots / Videos

_No response_

### Server Version and Plugins

Minecraft 1.20, Fabric loader 0.14.21, Fabric installer version 0.11.2

### Geyser Dump

https://dump.geysermc.org/owMb9b4T2XvyMoDuE4o6bXATuL0RFAOm

### Geyser Version

Geyser version 2.1.1-SNAPSHOT (git-master-4cd4729)

### Minecraft: Bedrock Edition Device/Version

All versions

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Konicai**
Items class modified using <https://github.com/GeyserMC/mappings-generator/pull/55/commits/6e0b9cddf3e8bc238221682e6c561f2b24bc20e2>

Closes #3843

### CODE REVIEW

File: core/src/main/java/org/geysermc/geyser/item/type/DecoratedPotItem.java [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+    }
+
+    @Override
+    public void translateNbtToBedrock(@NonNull GeyserSession session, @NonNull CompoundTag tag) {
+        super.translateNbtToBedrock(session, tag);
+
+        if (tag.remove("BlockEntityTag") instanceof CompoundTag blockEntityTag) {
+            if (blockEntityTag.remove("sherds") instanceof ListTag sherds) {
+                // bedrock wants it on the root level
+                tag.put(new ListTag("sherds", sherds.getValue()));
```
Comment (Camotoy) [inline core/src/main/java/org/geysermc/geyser/item/type/DecoratedPotItem.java:46]: Can't you just put the existing ListTag here instead of creating a new one?

**Review by Camotoy — APPROVED** [review]
Looks fine otherwise.

File: core/src/main/java/org/geysermc/geyser/item/type/DecoratedPotItem.java (hunk 1 above)
Comment (Konicai) [reply core/src/main/java/org/geysermc/geyser/item/type/DecoratedPotItem.java:46]: ah right, my initial version used wrong and different keys and it ended up like this
