### PR TITLE
Fix #5070 light block placement 

### LINKED ISSUE #5070: Light Source Block Placement Issue
### Describe the bug

After I place a light source block, it returns to my inventory, preventing me from using the light source block.

### To Reproduce

1. Pick up the light source block
2. Place the block on the floor

### Expected behaviour

I hope to fix the issue of not being able to place light source blocks

### Screenshots / Videos

_No response_

### Server Version and Plugins

server version : 1.20.4

Paper Plugins: (4):
- HuskHomes, MarriageMaster, Minepacks, TempFly
Bukkit Plugins: (92):
AntiCrasher, AnvilColors, AutomatedCrafting, AutomaticBroadcast, BetterDiscordSRV, BlepFishing, BlockLocker, ChatColor2, ChestSort, ChunkSpawnerLimiter
[13:48:19 INFO]:  Citizens, CMILib, ColoredSigns, CommandPanels, CoreProtect, CrossplatForms, CrossServer, DecentHolograms, DiscordSRV, DonateBot
FileSync, GeyserHacks, GlobalMarketPlus, GSit, Hat, HereTheData, Hurricane, InteractiveChat, InteractiveChatDiscordSrvAddon, InventoryRollbackPlus
InvisibleItemFrames, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, ItemEdit, ItemsAdder, LegendaryGuild, LibsDisguises, LiftReloaded, LiteSignIn
LoneLibs, LotteryItem, LuckPerms, MMOItems, MMRespawn, MoneyFromMobs, MythicCrucible, MythicLib, MythicMobs, NBTAPI
NoteBlockAPI, PlaceholderAPI, PlayerParticles, PlayerPoints, PlayerTask, PlayerTitle, PlugManX, PoaSK, PortableCraftingInvs, ProtocolLib
QuickShop-Hikari, RayTraceAntiXray, Residence, RPGInventory, SafariNet, SetSpawn, SharkMap, SharkPets, ShLevel, Shopkeepers
ShulkerBoxPreview, SimplePortals, SkBee, Skript, skript-reflect, SmartHealthScale, spark, Suicide, SuperHarvest, SuperVanish
TAB-Bridge, TakeMeBack, TradeMe, UltimateAutoRestart, UpgradeableHoppers, Vault, VentureChat, ViaBackwards, ViaVersion, Vulcan
WorldEdit, XConomy

### Geyser Dump

_No response_

### Geyser Version

Geyser-BungeeCord Build #682

### Minecraft: Bedrock Edition Device/Version

1.21.30 window10、Mobile version

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by patyhank**
See [Debug Logs](https://mclo.gs/CqWsE3K).
The Light Block identifier looks desync between java and bedrock.
So I fixed it.

### CODE REVIEW

File: core/src/main/java/org/geysermc/geyser/item/type/LightItem.java [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+public class LightItem extends BlockItem {
+
+    public LightItem(Builder builder, Block block, Block... otherBlocks) {
+        super(builder, block, otherBlocks);
+    }
+
+    @Override
+    public ItemData.Builder translateToBedrock(int count, DataComponents components, ItemMapping mapping, ItemMappings mappings) {
+        ItemMapping lightLevelMapping = getLightLevelMapping(components, mappings);
+        if (lightLevelMapping!= null) {
```
Comment (Camotoy) [inline core/src/main/java/org/geysermc/geyser/item/type/LightItem.java:47]: Add a space before `!=`

File: core/src/main/java/org/geysermc/geyser/registry/populator/ItemRegistryPopulator.java [hunk 2]
```diff
@@ -507,6 +508,26 @@ public static void populate() {
...
+
+            for (int i = 0; i <= Properties.LEVEL.high(); i++) {
+                ItemDefinition lightBlock = definitions.get("minecraft:light_block_"+i);
+                if (lightBlock == null) {
+                    break;
+                }
+
+                ItemMapping lightBlockEntry = ItemMapping.builder()
+                    .javaItem(Items.LIGHT)
+                    .bedrockIdentifier("minecraft:light_block_"+i)
```
Comment (Camotoy) [inline core/src/main/java/org/geysermc/geyser/registry/populator/ItemRegistryPopulator.java:522]: _" + i

File: core/src/main/java/org/geysermc/geyser/registry/type/ItemMappings.java [hunk 3]
```diff
@@ -134,6 +135,8 @@ public ItemMapping getMapping(ItemData data) {
             return ItemMapping.AIR;
         } else if (definition.getRuntimeId() == lodestoneCompass.getBedrockDefinition().getRuntimeId()) {
             return lodestoneCompass;
+        } else if (lightBlocks.containsKey(definition.getRuntimeId())) {
```
Comment (Camotoy) [inline core/src/main/java/org/geysermc/geyser/registry/type/ItemMappings.java:138]: This can be moved into its own `if` statement. `lightBlock = lightBlocks.get(definition.getRuntimeId()); if (lightBlock != null) return lightBlock;` (but with proper format)

File: core/src/main/java/org/geysermc/geyser/registry/populator/ItemRegistryPopulator.java [hunk 4]
```diff
@@ -507,6 +508,26 @@ public static void populate() {
                 javaItemToMapping.put(javaItem, mapping);
             }
 
+            // Add the light block level since it doesn't exist on java but we need it for item conversion
+            Int2ObjectMap<ItemMapping> lightBlocks = new Int2ObjectOpenHashMap<>();
+
+            for (int i = 0; i <= Properties.LEVEL.high(); i++) {
+                ItemDefinition lightBlock = definitions.get("minecraft:light_block_"+i);
```
Comment (Camotoy) [inline core/src/main/java/org/geysermc/geyser/registry/populator/ItemRegistryPopulator.java:515]: " + i)

**Review by Camotoy — APPROVED** [review]

File: core/src/main/java/org/geysermc/geyser/item/Items.java [hunk 5]
```diff
@@ -482,7 +482,7 @@ public final class Items {
     public static final Item RED_TERRACOTTA = register(new BlockItem(builder(), Blocks.RED_TERRACOTTA));
     public static final Item BLACK_TERRACOTTA = register(new BlockItem(builder(), Blocks.BLACK_TERRACOTTA));
     public static final Item BARRIER = register(new BlockItem(builder().rarity(Rarity.EPIC), Blocks.BARRIER));
-    public static final Item LIGHT = register(new BlockItem(builder().rarity(Rarity.EPIC), Blocks.LIGHT));
+    public static final Item LIGHT = register(new LightItem(builder().rarity(Rarity.EPIC), Blocks.LIGHT));
```
Comment (Camotoy) [inline core/src/main/java/org/geysermc/geyser/item/Items.java:485]: We will need to add this to the mappings generator. You don't need to make a PR; one of us can handle it.

Comment (patyhank) [reply core/src/main/java/org/geysermc/geyser/item/Items.java:485]: > We will need to add this to the mappings generator. You don't need to make a PR; one of us can handle it.

No need to make a PR, which part do you mean?
What changes do I need to make?

Comment (patyhank) [reply core/src/main/java/org/geysermc/geyser/item/Items.java:485]: Is it like adding code to https://github.com/GeyserMC/mappings-generator/blob/master/src/main/java/org/geysermc/generator/javaclass/GenerateItemsClass.java#L22 ?

Comment (Camotoy) [reply core/src/main/java/org/geysermc/geyser/item/Items.java:485]: Yes, but you don't have to make the PR yourself unless you want to. One of our team members can.

Comment (patyhank) [reply core/src/main/java/org/geysermc/geyser/item/Items.java]: Okay, I've undo changes of Items.java.

**Comment by Camotoy** [comment]
Please re-add the LightItem addition into the Items class, and then this will be good for merge. I will take care of the additional changes needed.
