### PR TITLE
Fix Squid Animation

### LINKED ISSUE #230: Squids don't have animation
When seeing a squid on Bedrock Edition, the animation is static and the squid does not turn sideways

### PR DESCRIPTION
**Pull request by davchoo**
This fixes #230.
This PR makes squids point in the correct direction, spin, and move their tentacles.
Their roll angle will differ from Java clients because the server only controls the speed of the roll animation.

### CODE REVIEW

File: connector/src/main/java/org/geysermc/connector/entity/player/SessionPlayerEntity.java [hunk 1]
```diff
@@ -104,6 +105,10 @@ public void updateBedrockMetadata(EntityMetadata entityMetadata, GeyserSession s
         if (entityMetadata.getId() == 0) {
             session.setSwimmingInWater((((byte) entityMetadata.getValue()) & 0x10) == 0x10 && metadata.getFlags().getFlag(EntityFlag.SPRINTING));
             refreshSpeed = true;
+        } else if (entityMetadata.getId() == 1) { // Air/bubbles
```
[the remark this answers is not in the document]
Comment (davchoo) [reply connector/src/main/java/org/geysermc/connector/entity/player/SessionPlayerEntity.java]: Should be addressed in d75eecd.

File: connector/src/main/java/org/geysermc/connector/entity/living/SquidEntity.java [hunk 2]
```diff
@@ -26,10 +26,67 @@
...
+        } else {
+            pitch += (-90 - pitch) * 0.02f;
+        }
+        moveAbsolute(session, position, Vector3f.from(yaw, 0, yaw), onGround, false);
+    }
+
+    @Override
+    public void setRotation(Vector3f rotation) {
+        // Let the Java server control yaw when the squid is out of water
+        if (!inWater) {
```
[the remark this answers is not in the document]
Comment (davchoo) [reply connector/src/main/java/org/geysermc/connector/entity/living/SquidEntity.java:65]: In my opinion, having separate variables for yaw and pitch was more descriptive than `rotation.getX()` and `rotation.getY()` when I was first working on the code. I guess it is better to use the rotation variable instead as it removes the need for overriding `getBedrockRotation` and initializing the yaw variable in the constructor. Though if the squid is out of the water, there would be an extra Vector3f created per tick in `setRotation`.

File: connector/src/main/java/org/geysermc/connector/entity/player/SessionPlayerEntity.java [hunk 3]
```diff
@@ -32,6 +32,7 @@
 import com.github.steveice10.mc.protocol.data.game.entity.metadata.Pose;
 import com.nukkitx.math.vector.Vector3f;
 import com.nukkitx.protocol.bedrock.data.AttributeData;
+import com.nukkitx.protocol.bedrock.data.entity.EntityData;
```
Comment (Camotoy) [inline connector/src/main/java/org/geysermc/connector/entity/player/SessionPlayerEntity.java:35]: Looks like this is an unnecessary import now.

**Comment by Camotoy** [comment]
Just tested in-game - it's beautiful. 

There is an entity status concerning squid rotation; is this relevant for us?

**Comment by davchoo** [comment]
The entity status is not relevant as we currently don't have control of the roll/spin of the squid or the angle of their tentacles.

File: connector/src/main/java/org/geysermc/connector/entity/living/SquidEntity.java [hunk 4]
```diff
@@ -26,10 +26,67 @@
...
 
-public class SquidEntity extends WaterEntity {
     public SquidEntity(long entityId, long geyserId, EntityType entityType, Vector3f position, Vector3f motion, Vector3f rotation) {
         super(entityId, geyserId, entityType, position, motion, rotation);
+        this.yaw = rotation.getX();
+    }
+
+    @Override
+    public void tick(GeyserSession session) {
+        checkInWater(session);
```
Comment (Camotoy) [inline connector/src/main/java/org/geysermc/connector/entity/living/SquidEntity.java:52]: On behalf of Redned:
`The in water check can be optimized
Should be checked only on a move packet being sent
Since I don’t think squids have their position updates on the mc server every single tick`

File: connector/src/main/java/org/geysermc/connector/utils/MathUtils.java [hunk 5]
```diff
@@ -60,6 +60,26 @@ public static double constrain(double num, double min, double max) {
         return num;
     }
 
+    /**
+     * If number is greater than the max, set it to max, and if number is lower than low, set it to low.
+     * @param num number to calculate
```
Comment (rtm516) [inline connector/src/main/java/org/geysermc/connector/utils/MathUtils.java:65]:
```suggestion
     * 
     * @param num number to calculate
```

File: connector/src/main/java/org/geysermc/connector/utils/MathUtils.java [hunk 6]
```diff
@@ -60,6 +60,26 @@ public static double constrain(double num, double min, double max) {
...
+     * @param max the greatest value the number can be
+     * @return - min if num is lower than min <br>
+     * - max if num is greater than max <br>
+     * - num otherwise
+     */
+    public static int constrain(int num, int min, int max) {
+        if (num > max) {
+            num = max;
+        }
+        if (num < min) {
```
Comment (rtm516) [inline connector/src/main/java/org/geysermc/connector/utils/MathUtils.java:76]:
```suggestion

        if (num < min) {
```

**Review by rtm516 — CHANGES_REQUESTED** [review]

File: connector/src/main/java/org/geysermc/connector/utils/MathUtils.java (hunk 6 above)
Comment (Camotoy) [reply connector/src/main/java/org/geysermc/connector/utils/MathUtils.java:76]: This also affects the constrain method for doubles in the same file. I'm fine with applying it here, but it should then be applied to the other function too while we're at it.

**Review by Camotoy — APPROVED** [review]
