### PR TITLE
Fix inconsistencies with movement and position

### LINKED ISSUE #204: Player can't move correctly when cord number is higher than 4096 / Slab and stair issues
**Describe the bug**
Players get dragged back by server when walking near a wall or getting out of water

**To Reproduce**
1. Use the newest inventory branch
2. build a wall two block(or higher) high
3. Walk near it

**Expected behavior**
Players can walk normally

**Screenshots**
See attached video file
video 1 and 2 for walking near wall
video 3 for getting out of water

**Server version**
spigot 1.15.2 latest build
**Geyser version**
Latest inventory branch

**Bedrock version**
Latest

**Additional context**
[video1](https://discordapp.com/channels/613163671870242838/613168464634576897/686762472522514515)
[video2](https://discordapp.com/channels/613163671870242838/613168464634576897/686762486401466388)
[video3:](https://discordapp.com/channels/613163671870242838/613168464634576897/686767428394287104)

### LINKED ISSUE #548: Carpets cause Bedrock Edition players to float
**Describe the bug**
When a bedrock player is standing on carpet, java players see them standing a half block up.

**To Reproduce**
image

**Expected behavior**
To not be floating above the carpet.

**Server Version**
This server is running Paper version git-Paper-282 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Previous version: git-Paper-273 (MC: 1.15.2)

**Geyser Version**
Geyser-Bukkit Build 140 with Floodgate

**Minecraft: Bedrock Edition Version**
Version 1.14.60
Build: 3968506

**Additional Context**
Don't know if this would affect it at all but I also have ViaVersion/ViaBackwards 3.0.0 SNAPSHOT and Vivecraft Spigot Extensions.

### PR DESCRIPTION
**Pull request by Heath123**
**`cache-chunks` needs to be enabled in your config for the move fixes to take effect!**

https://github.com/GeyserMC/mappings-generator/pull/18 needs to be merged first

The same as #669 which was accidentality closed and the branch deleted

Move fixes V2 using bounding boxes
Currently fixes #548, #1008 and #617
Might fix #204

**Known bugs that I can only fix when the custom collision boxes are in the release versions**
- Bamboo
- Some grindstone things
- Bugs with snow layers

**Known bugs to fix**
- [x] ~~Sometimes when sprinting up stairs you get teleported back~~ Fixed!
- [x] ~~Snow layers are a bit buggy (disabling optimisations 2 and 3 at the same time seems to help)~~ Mostly fixed, still has issues with different collision (not easily fixable but I'll try!)
- [x] ~~Add proper hitboxes for:~~ Now uses mappings
- Fences and Walls (also with carpets on top)
- Fence gates
- Grindstone
- [ ] Opening a fence gate, closing it and jumping is buggy
- [x] ~~Door collision is buggy~~ Fixed except for a specific arrangement
- [ ] NCP Passable correction could be closer to a real client

Please tell me about any more bugs you find!

### CODE REVIEW

**Comment by LegacyGamerHD** [comment]
is this even active?

**Comment by Heath123** [comment]
> is this even active?

Yes, it's very active, I just haven't pushed the latest changes yet. I have snow layers fixed etc.

**Comment by DoctorMacc** [comment]
Just a heads-up that some `.gradle` stuff got thrown in with the latest commit.

**Comment by Heath123** [comment]
> Just a heads-up that some `.gradle` stuff got thrown in with the latest commit.

Ah, I'll fix that, thank you

File: connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java [hunk 1]
```diff
@@ -64,12 +66,24 @@
     private boolean playerList = true;
     private final EntityEffectCache effectCache;
 
+    @Setter
+    private boolean sneaking;
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java:70]: This can be removed since Entity now has a Sneaking property.

File: connector/src/main/java/org/geysermc/connector/network/session/cache/TeleportCache.java [hunk 2]
```diff
@@ -29,20 +29,35 @@
...
-    private static final double ERROR = 0.2;
-    private static final double ERROR_Y = 0.5;
+    private static final double ERROR = 0.1;
+    private static final double ERROR_Y = 0.1;
 
-    private double x, y, z;
-    private int teleportConfirmId;
+    private int unconfirmedFor = 0;
+
+    // How many move packets the teleport can be unconfirmed for before it gets resent to the client
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/network/session/cache/TeleportCache.java:43]: This can be a Javadoc comment.

File: connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockBlockPickRequestTranslator.java [hunk 3]
```diff
@@ -1,100 +1,100 @@
...
+import org.geysermc.connector.inventory.Inventory;
+import org.geysermc.connector.network.session.GeyserSession;
+import org.geysermc.connector.network.translators.PacketTranslator;
+import org.geysermc.connector.network.translators.Translator;
+import org.geysermc.connector.network.translators.item.ItemEntry;
+import org.geysermc.connector.network.translators.item.ItemRegistry;
+import org.geysermc.connector.network.translators.world.block.BlockTranslator;
+
+@Translator(packet = BlockPickRequestPacket.class)
+public class BedrockBlockPickRequestTranslator extends PacketTranslator<BlockPickRequestPacket> {
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockBlockPickRequestTranslator.java:42]: This should probably be its own PR.

File: connector/src/main/java/org/geysermc/connector/network/translators/world/collision/CollisionRemapper.java [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+import java.lang.annotation.Repeatable;
+import java.lang.annotation.Retention;
+import java.lang.annotation.RetentionPolicy;
+
+@Retention(value = RetentionPolicy.RUNTIME)
+public @interface CollisionRemapper {
+
+    String regex();
+
+    // Defaults to matching any value
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/network/translators/world/collision/CollisionRemapper.java:38]: These can be Javadoc comments.

File: connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java (hunk 1 above)
Comment (DoctorMacc) [reply connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java:70]: Wait this is me being silly and thinking this is onGround. My bad!

**Comment by Heath123** [comment]
Fixes #1008

File: connector/src/main/java/org/geysermc/connector/network/session/cache/TeleportCache.java (hunk 2 above)
Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/session/cache/TeleportCache.java:43]: Done

File: connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockBlockPickRequestTranslator.java (hunk 3 above)
Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockBlockPickRequestTranslator.java:42]: I undid this

File: connector/src/main/java/org/geysermc/connector/network/translators/world/collision/CollisionRemapper.java (hunk 4 above)
Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/translators/world/collision/CollisionRemapper.java:38]: Done

File: connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java [hunk 5]
```diff
@@ -298,6 +316,71 @@ public void updateBedrockMetadata(EntityMetadata entityMetadata, GeyserSession s
...
+        } else {
+            // TODO: Make bounding box smaller when sneaking
+            boundingBox.setMiddleX(position.getX());
+            boundingBox.setMiddleY(position.getY() + 0.9); // (EntityType.PLAYER.getOffset() / 2));
+            // System.out.println("Offset: " + (EntityType.PLAYER.getOffset() / 2));
+            boundingBox.setMiddleZ(position.getZ());
+        }
+    }
+
+    public static final double COLLISION_TOLERANCE = 0.000001;
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java:336]: A Javadoc comment here would be nice.

Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java:341]: I might move this somewhere else or rename it, for now I'm just making it work

**Comment by Comstepr** [comment]
After testing, bamboo and snow layers are glitched, but stairs are fine.

**Comment by Heath123** [comment]
> After testing, bamboo and snow layers are glitched, but stairs are fine.

@Comstepr Snow layers should work, can can give more info about your setup please? Bamboo is very hard to fix but I'll give it a go.

File: .gitignore [hunk 6]
```diff
@@ -241,4 +241,7 @@ config.yml
 logs/
 public-key.pem
 locales/
-/cache/
\ No newline at end of file
+
+### VS Code ###
+.vscode
+cache/
```
Comment (DoctorMacc) [inline .gitignore:247]: Can you reset this back to `/cache/`? Otherwise it interferes with a folder in Geyser that's called cache.

**Comment by Heath123** [comment]
To do in a separate PR:

**Todo**
- [ ] Reproduce and fix #682, #617, #406, #460, #509 and #891
- [ ] Test with various anticheats (in progress)

File: .gitignore (hunk 6 above)
Comment (Heath123) [reply .gitignore]: Done

**Comment by EasyClifton** [comment]
Noice, 1.16.3, gonna test this tomorrow

**Comment by Heath123** [comment]
This isn't ready, there are a lot of things marked with TODO that I need to fix, but I'm marking this as not a draft to show that it might be ready to review and test.

File: connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java (hunk 5 above)
Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java]: Done

File: connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java [hunk 7]
```diff
@@ -221,6 +238,10 @@ public void updateRotation(GeyserSession session, float yaw, float pitch, boolea
     @Override
     public void setPosition(Vector3f position) {
         this.position = position.add(0, entityType.getOffset(), 0);
+        // If this is the player logged in through this Geyser session
+        if (geyserId == 1 && session != null) {
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java:242]: Why do we check for null here and nowhere else? Because we check for `geyserId`, `session` should never be null.

File: connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java [hunk 8]
```diff
@@ -751,4 +803,109 @@ public void sendAdventureSettings() {
...
+                playerBoundingBox.setSizeY(1.8);
+            }
+        }
+    }
+
+    /**
+     * Additional space where blocks are checked, which is helpful for fixing NoCheatPlus's Passable check.
+     * This check doesn't allow players right up against the block, so they must be pushed slightly away.
+     */
+    public static final double COLLISION_TOLERANCE = 0.00001; // TODO: Move?
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java:856]: Static variables should be at the top of the file.

File: connector/src/main/java/org/geysermc/connector/network/session/cache/TeleportCache.java [hunk 9]
```diff
@@ -29,20 +29,37 @@
 import com.nukkitx.math.vector.Vector3f;
 import lombok.AllArgsConstructor;
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/network/session/cache/TeleportCache.java:30]: We can probably remove this import?

File: connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockActionTranslator.java [hunk 10]
```diff
@@ -1,168 +1,168 @@
...
+import com.github.steveice10.mc.protocol.packet.ingame.client.player.ClientPlayerActionPacket;
+import com.github.steveice10.mc.protocol.packet.ingame.client.player.ClientPlayerStatePacket;
+import com.nukkitx.math.vector.Vector3i;
+import com.nukkitx.protocol.bedrock.data.LevelEventType;
+import com.nukkitx.protocol.bedrock.data.entity.EntityEventType;
+import com.nukkitx.protocol.bedrock.packet.EntityEventPacket;
+import com.nukkitx.protocol.bedrock.packet.LevelEventPacket;
+import com.nukkitx.protocol.bedrock.packet.PlayStatusPacket;
+import com.nukkitx.protocol.bedrock.packet.PlayerActionPacket;
+import org.geysermc.connector.entity.PlayerEntity;
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockActionTranslator.java:42]: This can be reverted.

File: connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockMovePlayerTranslator.java [hunk 11]
```diff
@@ -59,26 +66,64 @@ public void translate(MovePlayerPacket packet, GeyserSession session) {
...
         // lose precision and thus, causes players to get stuck when walking near walls
-        double javaY = packet.getPosition().getY() - EntityType.PLAYER.getOffset();
-        if (packet.isOnGround()) javaY = Math.ceil(javaY * 2) / 2;
+        double javaY = Double.parseDouble(Float.toString(packet.getPosition().getY())) - EntityType.PLAYER.getOffset();
 
         Vector3d position = Vector3d.from(Double.parseDouble(Float.toString(packet.getPosition().getX())), javaY,
                 Double.parseDouble(Float.toString(packet.getPosition().getZ())));
 
-        if(!session.confirmTeleport(position)){
+        if (!session.confirmTeleport(position)){
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockMovePlayerTranslator.java:94]: `if (!session.confirmTeleport(position)) {`

File: connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockMovePlayerTranslator.java [hunk 12]
```diff
@@ -59,26 +66,64 @@ public void translate(MovePlayerPacket packet, GeyserSession session) {
...
         if (!isValidMove(session, packet.getMode(), entity.getPosition(), packet.getPosition())) {
             session.getConnector().getLogger().debug("Recalculating position...");
             recalculatePosition(session, entity, entity.getPosition());
             return;
         }
 
         ClientPlayerPositionRotationPacket playerPositionRotationPacket = new ClientPlayerPositionRotationPacket(
-                packet.isOnGround(), position.getX(), position.getY(), position.getZ(), packet.getRotation().getY(), packet.getRotation().getX()
+                packet.isOnGround(), position.getX(),
+                Math.round(position.getY() * 10000.0D) / 10000.0d,
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockMovePlayerTranslator.java:123]: What in the world is this for?

File: connector/src/main/java/org/geysermc/connector/network/translators/world/collision/translators/BlockCollision.java [hunk 13]
```diff
@@ -0,0 +1,149 @@
...
+import org.geysermc.connector.utils.MathUtils;
+
+import javax.xml.transform.sax.SAXSource;
+
+@EqualsAndHashCode
+public class BlockCollision {
+
+    protected BoundingBox[] boundingBoxes;
+
+    protected int x, y, z;
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/network/translators/world/collision/translators/BlockCollision.java:43]: Though this may look cleaner, traditionally all variables have been declared on their own line.

File: connector/src/main/java/org/geysermc/connector/network/translators/world/collision/translators/BlockCollision.java [hunk 14]
```diff
@@ -0,0 +1,149 @@
...
+
+    // This is used for the step up logic.
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/network/translators/world/collision/translators/BlockCollision.java:45]: These comments can probably just become a Javadoc comment.

File: connector/src/main/java/org/geysermc/connector/network/translators/world/collision/translators/BlockCollision.java [hunk 15]
```diff
@@ -0,0 +1,149 @@
...
+    @EqualsAndHashCode.Exclude
+    protected double pushUpTolerance = 1;
+
+    public void setPosition(int x, int y, int z) {
+        this.x = x;
+        this.y = y;
+        this.z = z;
+    }
+
+    // Overridden in classes like SnowCollision when correction code needs to be run before the main correction
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/network/translators/world/collision/translators/BlockCollision.java:60]: Javadoc comment

**Review by DoctorMacc — CHANGES_REQUESTED** [review]

File: connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java (hunk 7 above)
Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java:242]: It's null when the position is set for the first time (I think by the constructor of Entity)

File: connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java (hunk 8 above)
Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java]: Done

File: connector/src/main/java/org/geysermc/connector/network/session/cache/TeleportCache.java (hunk 9 above)
Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/session/cache/TeleportCache.java]: Done

File: connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockActionTranslator.java (hunk 10 above)
Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockActionTranslator.java]: I think this is done now

File: connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockMovePlayerTranslator.java (hunk 11 above)
Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockMovePlayerTranslator.java:94]: ?

Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockMovePlayerTranslator.java:94]: Oh

Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockMovePlayerTranslator.java]: Fixed

File: connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockMovePlayerTranslator.java (hunk 12 above)
Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockMovePlayerTranslator.java:123]: It might be leftover debug code, or it might be to solve precision issues. I'll make sure everything still works without it.

Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockMovePlayerTranslator.java]: Fixed

File: connector/src/main/java/org/geysermc/connector/network/translators/world/collision/translators/BlockCollision.java (hunk 13 above)
Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/translators/world/collision/translators/BlockCollision.java]: Done

File: connector/src/main/java/org/geysermc/connector/network/translators/world/collision/translators/BlockCollision.java (hunk 14 above)
Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/translators/world/collision/translators/BlockCollision.java]: Done

File: connector/src/main/java/org/geysermc/connector/network/translators/world/collision/translators/BlockCollision.java (hunk 15 above)
Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/translators/world/collision/translators/BlockCollision.java]: Done

**Comment by Hellohi3654** [comment]
Hey circuit10 after merging the lastest commits from your move-fixes branch I have noticed that whenever a bedrock player is teleported to a position outside of their loaded chunks, that the chunks refuse to load for the player but if the player is teleported between worlds the chunks will load for them then
So basically to teleport a bedrock player you have to tp them to the nether then to the position in the overworld overwise when they are teleported the chunks don't load for them

**Comment by DoctorMacc** [comment]
There are custom mappings but they should be provided in this branch. Do you have cache-chunks enabled?

**Comment by DoctorMacc** [comment]
And also please provide the packet errors.

**Comment by IMS212** [comment]
I do not have chunk caching on, and here is the packet error: https://pastebin.com/cSpppawQ

**Comment by DoctorMacc** [comment]
Ah, that error is unrelated and something we've fixed in the master branch. You need to turn on chunk caching to get the move fixes.

**Comment by IMS212** [comment]
oh, ill try that. thanks!

**Comment by IMS212** [comment]
Ok, i've actually found another rather specific issue (i've done literally no testing, just documenting this) where if you're on an soul sand block, then you walk up to a slab with soul sand under it, then the rubber banding occurs. I just experienced this and i don't know if it can be triggered any other way, and i get no errors in console.

File: connector/src/main/java/org/geysermc/connector/network/translators/java/entity/player/JavaPlayerPositionRotationTranslator.java [hunk 16]
```diff
@@ -1,123 +1,124 @@
...
+        double newZ = packet.getZ() +
+                (packet.getRelative().contains(PositionElement.Z) ? entity.getPosition().getZ() : 0);
+
+        double newPitch = packet.getPitch() +
+                (packet.getRelative().contains(PositionElement.PITCH) ? entity.getBedrockRotation().getX() : 0);
+        double newYaw = packet.getYaw() +
+                (packet.getRelative().contains(PositionElement.YAW) ? entity.getBedrockRotation().getY() : 0);
+
+        session.addTeleport(new TeleportCache(newX, newY, newZ, newPitch, newYaw, packet.getTeleportId()));
+        entity.moveAbsolute(session, Vector3f.from(newX, newY, newZ), (float) newYaw, (float) newPitch, true, true);
```
[the remark this answers is not in the document]
Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/translators/java/entity/player/JavaPlayerPositionRotationTranslator.java:122]: I think what causes is the chunk bug on teleport is that the server won't send chunks until the client accepts the teleport, but currently that doesn't happen until the client sends a move packet, which doesn't happen until the chunks are loaded.
If I manually send the conformation packet with [pakkit](https://github.com/Heath123/pakkit) the chunks load.

[the remark this answers is not in the document]
Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/translators/java/entity/player/JavaPlayerPositionRotationTranslator.java:122]: OK, fixed it by also allowing look-only packets to confirm teleports

[the remark this answers is not in the document]
Comment (Hellohi3654) [reply connector/src/main/java/org/geysermc/connector/network/translators/java/entity/player/JavaPlayerPositionRotationTranslator.java:122]: Cool thanks

**Comment by YaUhYeah** [comment]
Is maybe known, but i tried to test latest move fixes build and when geyser is enabling is get this error: 
https://pastebin.com/RrEzQ7t0
IDK Maybe known.

**Comment by rtm516** [comment]
> Is maybe known, but i tried to test latest move fixes build and when geyser is enabling is get this error:
> https://pastebin.com/RrEzQ7t0
> IDK Maybe known.

This is because you built it manually, I suggest downloading a build from the checks tab then clicking artefacts.
https://github.com/GeyserMC/Geyser/pull/699/checks

**Comment by YaUhYeah** [comment]
> > Is maybe known, but i tried to test latest move fixes build and when geyser is enabling is get this error:
> > https://pastebin.com/RrEzQ7t0
> > IDK Maybe known.
> 
> This is because you built it manually, I suggest downloading a build from the checks tab then clicking artefacts.
> https://github.com/GeyserMC/Geyser/pull/699/checks

Hello, yes I did that, and thats when it happened.

**Comment by Heath123** [comment]
It must not be including the right files then, I'll debug it later

File: connector/src/main/java/org/geysermc/connector/utils/MathUtils.java [hunk 17]
```diff
@@ -25,6 +25,8 @@
 
 package org.geysermc.connector.utils;
 
+import com.nukkitx.math.vector.Vector3d;
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/utils/MathUtils.java:28]: Unused import?

File: connector/src/main/java/org/geysermc/connector/utils/MathUtils.java [hunk 18]
```diff
@@ -75,7 +77,7 @@ public static Byte convertByte(Object value) {
         return (Byte) value;
     }
 
-    /**
+     /*
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/utils/MathUtils.java:80]: ??

File: connector/src/main/java/org/geysermc/connector/network/translators/world/collision/translators/OtherCollision.java [hunk 19]
```diff
@@ -0,0 +1,61 @@
...
+public class OtherCollision extends BlockCollision {
+
+    public OtherCollision(ArrayNode collisionList, String ID) { // TODO: remove id
+        super();
+        boundingBoxes = new BoundingBox[collisionList.size()];
+
+        for (int i = 0; i < collisionList.size(); i++)
+        {
+            ArrayNode collisionBoxArray = (ArrayNode) collisionList.get(i);
+            boundingBoxes[i] = new BoundingBox(collisionBoxArray.get(0).asDouble(),
```
Comment (Hellohi3654) [inline connector/src/main/java/org/geysermc/connector/network/translators/world/collision/translators/OtherCollision.java:44]: Moves fixes have broke for me every since this was changed a few days ago

Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/translators/world/collision/translators/OtherCollision.java:44]: Is the problem with north-facing stairs?

**Comment by YaUhYeah** [comment]
I think the world not loading when teleporting still happens. Not sure if u tried to fix it or not.

**Comment by Heath123** [comment]
> I think the world not loading when teleporting still happens. Not sure if u tried to fix it or not.

Hmm, that should be fixed now

File: connector/src/main/java/org/geysermc/connector/network/translators/world/collision/translators/OtherCollision.java (hunk 19 above)
Comment (Hellohi3654) [reply connector/src/main/java/org/geysermc/connector/network/translators/world/collision/translators/OtherCollision.java:44]: any direction

**Comment by Hellohi3654** [comment]
> I think the world not loading when teleporting still happens. Not sure if u tried to fix it or not.

That's fixed

File: connector/src/main/java/org/geysermc/connector/network/translators/world/collision/translators/OtherCollision.java (hunk 19 above)
Comment (Hellohi3654) [reply connector/src/main/java/org/geysermc/connector/network/translators/world/collision/translators/OtherCollision.java:44]: slabs everything

**Comment by Heath123** [comment]
@YaUhYeah When is it happening? Can you give more info please?

**Comment by Hellohi3654** [comment]
> @YaUhYeah When is it happening? Can you give more info please?

I'm pretty sure they just hasn't updated I no longer have this problem

**Comment by YaUhYeah** [comment]
> > @YaUhYeah When is it happening? Can you give more info please?
> 
> I'm pretty sure they just hasn't updated I no longer have this problem

Wierd no I am definitely using the latest move fixes, its the same as before when i teleport far away chunks not load :(

**Comment by Heath123** [comment]
Note to self: https://github.com/NoCheatPlus/NoCheatPlus/pull/47

File: connector/src/main/java/org/geysermc/connector/utils/MathUtils.java (hunk 18 above)
Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/utils/MathUtils.java]: Fixed

File: connector/src/main/java/org/geysermc/connector/utils/MathUtils.java (hunk 17 above)
Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/utils/MathUtils.java]: Fixed

File: connector/src/main/java/org/geysermc/connector/entity/player/PlayerEntity.java [hunk 20]
```diff
@@ -223,6 +223,16 @@ public void setPosition(Vector3f position) {
...
+    /**
+     * Set the player position without adding the entity type's offset. Used when the player sends us a move packet
+     * where the offset is already added
+     *
+     * @param position the new position of the Bedrock player
+     */
+    public void setPositionWithoutOffset(Vector3f position) {
+        this.position = position;
+    }
+
```
Comment (RednedEpic) [inline connector/src/main/java/org/geysermc/connector/entity/player/PlayerEntity.java:235]: This method should be removed and instead updated with:
```suggestion
    public void setPosition(Vector3f position, boolean includeOffset) {
        this.position = includeOffset ? position.add(0, entityType.getOffset(), 0) : position;
    }
```
Then just have the current `setPosition` overload this method.

File: connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockMovePlayerTranslator.java [hunk 21]
```diff
@@ -155,6 +152,53 @@ public boolean isValidMove(GeyserSession session, MovePlayerPacket.Mode mode, Ve
         return true;
     }
 
+    /**
+     * Adjust the Bedrock position before sending to the Java server to account for inaccuracies in movement between
+     * the two versions.
```
Comment (RednedEpic) [inline connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockMovePlayerTranslator.java:157]: Should state somewhere in this doc that returning `null` means the movement packet will be cancelled (as documented in the `translate` method of this class.

File: connector/src/main/java/org/geysermc/connector/network/translators/collision/CollisionRemapper.java [hunk 22]
```diff
@@ -0,0 +1,52 @@
...
+package org.geysermc.connector.network.translators.collision;
+
+import java.lang.annotation.Repeatable;
+import java.lang.annotation.Retention;
+import java.lang.annotation.RetentionPolicy;
+
+@Retention(value = RetentionPolicy.RUNTIME)
+public @interface CollisionRemapper {
+
+    String regex();
```
Comment (RednedEpic) [inline connector/src/main/java/org/geysermc/connector/network/translators/collision/CollisionRemapper.java:35]: For consistency, may be worth documenting this too.

**Review by RednedEpic — CHANGES_REQUESTED** [review]

File: connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockMovePlayerTranslator.java (hunk 21 above)
Comment (DoctorMacc) [reply connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockMovePlayerTranslator.java:157]: This is mentioned in the return value.

File: connector/src/main/java/org/geysermc/connector/network/translators/collision/CollisionRemapper.java (hunk 22 above)
Comment (DoctorMacc) [reply connector/src/main/java/org/geysermc/connector/network/translators/collision/CollisionRemapper.java:35]: @Heath123

File: connector/src/main/java/org/geysermc/connector/network/translators/collision/BoundingBox.java [hunk 23]
```diff
@@ -0,0 +1,60 @@
...
+
+    public void translate(double x, double y, double z) {
+        middleX += x;
+        middleY += y;
+        middleZ += z;
+    }
+
+    // Check intersection with no offset
+    // Currently never used, but will probably be useful in the future
+    /* public boolean checkIntersection(BoundingBox otherBox) {
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/network/translators/collision/BoundingBox.java:49]: I think we should get rid of this - if we need it, we can check old git commits.

File: connector/src/main/java/org/geysermc/connector/network/translators/collision/CollisionRemapper.java (hunk 22 above)
Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/translators/collision/CollisionRemapper.java:35]: OK, I will

Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/translators/collision/CollisionRemapper.java:39]: Done

File: connector/src/main/java/org/geysermc/connector/network/translators/collision/BoundingBox.java (hunk 23 above)
Comment (Heath123) [reply connector/src/main/java/org/geysermc/connector/network/translators/collision/BoundingBox.java]: Done

**Comment by Hellohi3654** [comment]
The player is kicked out of boats when entering
I believe this is caused by move fixes

**Comment by Heath123** [comment]
> The player is kicked out of boats when entering
> I believe this is caused by move fixes

I can get in boats

File: connector/src/main/resources/config.yml [hunk 24]
```diff
@@ -151,4 +151,8 @@ enable-proxy-connections: false
 # 1400 is the default.
 # mtu: 1400
 
+# Whether to use direct server methods to retrieve information such as block states.
+# Turning this off for Spigot will stop NMS from being used but will have a performance impact.
+use-adapters: true
+
```
Comment (Heath123) [inline connector/src/main/resources/config.yml:157]: Should we have an option for move fixes too?

Comment (DoctorMacc) [reply connector/src/main/resources/config.yml:157]: While I'm not opposed, I see no reason. There's not much reason people would want the move fixes off, and performance shouldn't be an issue. The reason that is an issue is in case there's a Spigot instance that breaks with them enabled.

Something that *could* be a config option is teleport ID confirmation flexibility.

Comment (Heath123) [reply connector/src/main/resources/config.yml:157]: You mean the position and resend thresholds?

Comment (DoctorMacc) [reply connector/src/main/resources/config.yml:157]: Yes.

**Comment by EasyClifton** [comment]
When was this renamed?

**Comment by DoctorMacc** [comment]
I renamed it a couple weeks ago.

**Review by DoctorMacc — APPROVED** [review]

**Comment by soshimee** [comment]
Hmm, wonder why it says "sprinting up stairs," walking was the worst part for me, sprinting didn't have any issues.
