### PR TITLE
Fix Skin Caching and Fix Skin Restorer

### LINKED ISSUE #518: Invinsible players from BE side
**Describe the bug**

BE Players won't be able to see JE players in some scenarios (ex. a player joning a duels game or a skywars game)
**To Reproduce**
For me, it was joining a Duels game using the Duels plugin and that's it

**Expected behavior**

JE players appearing normally
**Screenshots / Videos**

https://streamable.com/z9k5az (Just take the Invinsible player thing from the vid only, the other bugs were fixed by just downgrading the ViaVersion plugin)
**Server Version**

This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Geyser Version**

build number 128
**Minecraft: Bedrock Edition Version**

1.14.60
**Additional Context**

LOG: https://pastebin.com/raw/hC1n1xva

### PR DESCRIPTION
**Pull request by bundabrg**
Changes:
* Instead of caching a skin based upon the player we cached it based upon the textureURL. This means multiple players with the same skin will benefit from the cache and more importantly will mean a player changing their skin will not get a false cache hit.
* This should fix all issues with SkinRestorer and will now correctly show the skin both to the player themselves and to other players
* Bedrock seems to cache the skin internally based upon the fullSkinId. Setting this to the textureUrl effectively makes it unique as well.

Video: https://youtu.be/BUpN3y5eQFk

Closes #518

## Still To Do

* [x] Fix playerlist properly. Right now async loading of skins interferes with the regular java playerlist packet and if it comes out of order the wrong skin can get applied or even worse get expelled (from the game by crashing)
* [X] Implement image caching
* [X] Implement image expiring

## Bugs
* [ ] Sometimes when logging in a players own skin is not set. I think it sets correctly then overwrites it with a default due to race issues
* [x] Expiring is not working and will always expire images. 

## Changes
* Minimize Player Updates
* Cache skins based on TextureUrl
* Optional Disk caching of all images
* Memory cache will use timed evictions to eliminate memory leak
* Provide caching for all images (capes, ears)
* Force skins as trusted

### CODE REVIEW

**Comment by bundabrg** [comment]
Note a known issue at the moment is my NPC skin is not working.
What seems to happen is when logging in the player briefly see's the correct skin, then it turns into a Steve skin. Packets show that the correct PlayerList packet is sent, then immediately followed up with a Steve PlayerList packet. There must be an empty skin being sent somewhere and previously it was ignored because the code cached sending skin updates from a player rather than by unique skin whereas now it will send it.

**Comment by E404NNF** [comment]
I will test it on hypixel soon

**Comment by E404NNF** [comment]
It works!, I can see my teammate on bedwars now

**Comment by bundabrg** [comment]
Added Todo: Fix playerlist properly. Right now async loading of skins interferes with the regular java playerlist packet and if it comes out of order the wrong skin can get applied or even worse, get expelled (from the game by crashing)

**Comment by bundabrg** [comment]
Still something not fully right as bedrock players can crash when switching worlds.

**Comment by bundabrg** [comment]
After extensive testing I think the crashing bug is not related to this but when its used in combination with #656.

**Comment by Tim203** [comment]
There is no need for a cache interval now since a textureId stands for one (unique) image.
I also suggest that we switch to (Guava's Caches)[https://github.com/google/guava/wiki/CachesExplained]. This will automatically remove entries after the specified time (I suggest 20 minutes instead of 30, the cache interval in your PR). This will probably fix some memory issues as well since we actually never remove entries and only update them after the cache interval.

**Comment by bundabrg** [comment]
Due to the large number of web requests I recommend that the images be cached in a folder as well based upon their textureURL which should greatly speed things up and allow Geyser to be a good netizen.

This can be an option as it will take up space and we can touch the modification date of a file when read to indicate its last usage so that unused files can be purged based upon modification date.

I'm thinking an option like:
```yaml
# How long to cache skins for in days. 0 will disable caching.
cache-skins: 180
```

**Comment by bundabrg** [comment]
As of the last update the system will now cache skins to disk if the configuration variable "cache-skins" is set to a non 0 value.

Any suggestions on best place to implement the expiry of old files? Is there a cleanup or maintenance task running periodically somewhere?

**Comment by bundabrg** [comment]
I'm thinking I might instead rename to cache-images and make the caching more generic so it will cache capes, plus any other images we need. It's quite useful when used with #683.

**Comment by bundabrg** [comment]
[1.16 Version](https://github.com/bundabrg/Geyser/tree/fix/skin-caching-1.16)

File: bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongeConfiguration.java [hunk 1]
```diff
@@ -149,6 +149,11 @@ public boolean isCacheChunks() {
         return node.getNode("cache-chunks").getBoolean(false);
     }
 
+    @Override
+    public int getCacheImages() {
+        return node.getNode("cache-skins").getInt(0);
```
Comment (DoctorMacc) [inline bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongeConfiguration.java:154]: This should be consistent with the `GeyserJacksonConfiguration` default property.

File: connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java [hunk 2]
```diff
@@ -47,7 +47,7 @@
 import org.geysermc.connector.scoreboard.Team;
 import org.geysermc.connector.utils.AttributeUtils;
 import org.geysermc.connector.utils.MessageUtils;
-import org.geysermc.connector.utils.SkinUtils;
+import org.geysermc.connector.network.session.cache.EntityEffectCache;
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java:50]: Put this import in alphabetical order.

File: connector/src/main/java/org/geysermc/connector/utils/SkinProvider.java [hunk 3]
```diff
@@ -53,8 +55,8 @@
     public static final Skin EMPTY_SKIN = new Skin(-1, "steve", STEVE_SKIN);
     public static final byte[] ALEX_SKIN = new ProvidedSkin("bedrock/skin/skin_alex.png").getSkin();
     public static final Skin EMPTY_SKIN_ALEX = new Skin(-1, "alex", ALEX_SKIN);
-    private static Map<UUID, Skin> cachedSkins = new ConcurrentHashMap<>();
-    private static Map<UUID, CompletableFuture<Skin>> requestedSkins = new ConcurrentHashMap<>();
+    private static Map<String, Skin> cachedSkins = new ConcurrentHashMap<>();
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/utils/SkinProvider.java:58]: There's a couple of imports here that can be marked as final - might as well clean that up now if possible.

File: connector/src/main/java/org/geysermc/connector/utils/SkinUtils.java [hunk 4]
```diff
@@ -31,6 +31,8 @@
 import com.nukkitx.protocol.bedrock.data.skin.ImageData;
 import com.nukkitx.protocol.bedrock.data.skin.SerializedSkin;
 import com.nukkitx.protocol.bedrock.packet.PlayerListPacket;
+
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/utils/SkinUtils.java:34]: Remove this unnecessary space.

File: connector/src/main/java/org/geysermc/connector/utils/SkinUtils.java [hunk 5]
```diff
@@ -31,6 +31,8 @@
...
+import com.nukkitx.protocol.bedrock.packet.PlayerSkinPacket;
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/utils/SkinUtils.java:35]: This import is unused.

File: connector/src/main/java/org/geysermc/connector/utils/SkinUtils.java [hunk 6]
```diff
@@ -201,48 +216,44 @@ public static void requestAndHandleSkinAndCape(PlayerEntity entity, GeyserSessio
...
+                                        geometry.getGeometryData()
+                                );
+
+
+                                PlayerListPacket playerAddPacket = new PlayerListPacket();
+                                playerAddPacket.setAction(PlayerListPacket.Action.ADD);
+                                playerAddPacket.getEntries().add(updatedEntry);
+                                session.sendUpstreamPacket(playerAddPacket);
+
+//                                // Update SKin
```
Comment (DoctorMacc) [inline connector/src/main/java/org/geysermc/connector/utils/SkinUtils.java:241]: Remove these comments if you're not going to need it.

**Comment by bundabrg** [comment]
Ok that was the final issue sorted. There is still a hard to reproduce bug where sometimes the bedrock player doesn't see their own skin on login but it normally corrects soon and doesn't affect others seeing them so not a deal-breaker. This is now ready for merge.

**Comment by bundabrg** [comment]
And I just realised that may be related to FastLogin as it also sends skins and is easily disabled in its own config.

**Comment by Comstepr** [comment]
Are they supposed to have like a punisher skin?

File: bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongeConfiguration.java [hunk 7]
```diff
@@ -149,6 +149,11 @@ public boolean isCacheChunks() {
         return node.getNode("cache-chunks").getBoolean(false);
     }
 
+    @Override
+    public int getCacheImages() {
+        return node.getNode("cache-skins").getInt(180);
```
Comment (DoctorMacc) [inline bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongeConfiguration.java:154]: This should probably be 0 if the default config option is 0 and we're not bumping up the config version (which I don't see us needing to do).

**Comment by DoctorMacc** [comment]
Code looks fine to me.

**Comment by Comstepr** [comment]
Are they supposed to have like a punisher skin?

File: bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongeConfiguration.java (hunk 7 above)
Comment (bundabrg) [reply bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongeConfiguration.java:154]: The default config option is 180 at the moment .

Comment (DoctorMacc) [reply bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongeConfiguration.java:154]: ...Not in this PR?

Comment (bundabrg) [reply bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongeConfiguration.java:154]: https://github.com/GeyserMC/Geyser/pull/680/files#diff-68f00d4835b63f4044aa98523047c86aR92

Comment (DoctorMacc) [reply bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongeConfiguration.java:154]: https://github.com/GeyserMC/Geyser/blob/aad3c2357158b4f8264c7ba4ed5676bf3a6297ef/connector/src/main/resources/config.yml#L94

Comment (bundabrg) [reply bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongeConfiguration.java:154]: oh the config file, totally forgot about that. Well lets just set them all to 0 since it feels more logical anyway as per discord discussion. I'll do that later today and rebase.

Comment (DoctorMacc) [reply bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongeConfiguration.java:154]: :+1:

**Comment by bundabrg** [comment]
I've been cleaning up the memory cache and now we cache skins and capes for a maximum of an hour in memory and will reload (with from internet or disk) once its evicted. It uses the last accessed time.

This just needs to be tested for a couple of days but should it all be fine it'll be fine for a merge.

File: connector/src/main/java/org/geysermc/connector/utils/SkinProvider.java [hunk 8]
```diff
@@ -102,22 +110,44 @@
...
+                        //noinspection ResultOfMethodCallIgnored
+                        imageFile.delete();
+                        count++;
+                    }
+                }
+
+                if (count > 0) {
+                    GeyserConnector.getInstance().getLogger().debug(String.format("Removed %d cached image files as they have expired", count));
+                }
+            }, 10, 1440, TimeUnit.MINUTES);
```
Comment (rtm516) [inline connector/src/main/java/org/geysermc/connector/utils/SkinProvider.java:135]: Should this be ajusted to be 2x the expiry time? Making it clean up faster
