### PR TITLE
More accurate pose switching behaviour.

### LINKED ISSUE #5986: Sneaking while swimming changes the hitbox to normal hitbox.
### Describe the bug

While swimming, sneaking changes your hitbox from the swimming state to the normal sneak hitbox. When you cancel sneak, it reverts to the normal hitbox.

### To Reproduce

Sneak while swimming

### Expected behaviour

It should remain the same as the hitbox when swimming.

### Screenshots / Videos

_No response_

### Server Version and Plugins

Velocity 3.4.0-SNAPSHOT (git-a046f700-b557)
velocity, antipopup, consolespamfixreborn, floodgate, luckperms, foxgate, geyser, libertybans, mckotlin-velocity, packetevents, serverlinks, signedvelocity, skinsrestorer, velocity-scoreboard-api, vlobby, voicechat

Purpur 1.21.10-2522
CommandPanels, PrefiX, SignedVelocity, AdvancedReplay, AxSmithing, BedWars, BungeeGuard, Citizens, ClicksLimiterZ, ConsoleSpamFixReborn, CoreProtect, DiscordSRV, Essentials, floodgate, Floodgate-Skript, FreedomChat, GrapplingHook, GrimAC, GSit, ImageFrame, JukeBox, JumpPads, LuckPerms, LunaChat, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, NoteBlockAPI, OldCombatMechanics, OpenInv, packetevents, PlaceholderAPI, ProtocolLib, RealTimePlugin, Report, SBA, SkinsRestorer, Skript, skript-placeholders, skript-reflect, Skywars, TAB, TNTRun, TotemGuard, UpOnlyKB, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, voicechat, voicechat-discord, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/NLp0FWylT2H27CsmxVc17kmEx5T2dbNo

### Geyser Version

2.9.0-b980

### Minecraft: Bedrock Edition Device/Version

1.21.123

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by oryxel1**
Does what it said, the client update this pose every tick so we do the same! Resolve #5986

### CODE REVIEW

File: core/src/main/java/org/geysermc/geyser/entity/type/player/AvatarEntity.java [hunk 1]
```diff
@@ -346,7 +350,7 @@ public void setDimensionsFromPose(Pose pose) {
                 height = 0.6f;
                 width = definition.width();
             }
-            case DYING -> {
+            case DYING, SLEEPING -> {
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/entity/type/player/AvatarEntity.java]: This would be handled in `super.setDimensionFromPose()`:
image

Comment (oryxel1) [reply core/src/main/java/org/geysermc/geyser/entity/type/player/AvatarEntity.java]: oops.

File: core/src/main/java/org/geysermc/geyser/entity/type/player/AvatarEntity.java [hunk 2]
```diff
@@ -322,15 +322,19 @@ public void setPose(Pose pose) {
...
+                    updateRotation(this.yaw, 0, this.onGround);
+                }
             }
         }
     }
 
     @Override
     public void setPitch(float pitch) {
-        super.setPitch(getFlag(EntityFlag.CRAWLING) ? 0 : pitch);
+        super.setPitch(getFlag(EntityFlag.CRAWLING) && !(this instanceof SessionPlayerEntity) ? 0 : pitch);
```
Comment (Camotoy) [inline core/src/main/java/org/geysermc/geyser/entity/type/player/AvatarEntity.java:337]: Can this be an override in the SessionPlayerEntity class instead?
