### PR TITLE
Follows specified address/port in remote config for plugin versions: fix #1110

### LINKED ISSUE #1110: Bungeecord plugin: Specifying address/port in remote config doesn't work
**Describe the bug**

Changing the config of `remote` selection in `plugins/Geyser-BungeeCord/config.yml` doesn't take effect. The plugin gets the host info only from the Waterfall config.

We are using Waterfall behind a haproxy server with Waterfall's `proxy_protocol` enabled. Directly connect to the server with Waterfall's listening host using Minecraft JE causes `Timed out` error. We tried to change the remote host to haproxy server but changing the remote address and port in Geyser's config file doesn't work.

We tried to use standalone version to connect to the haproxy address and everything works well. With Bungeecord plugin version it always says `Read time out` in console(It connects to Waterfall directly).
```
[23:15:25 INFO] [Geyser-BungeeCord]: User has disconnected from remote Java server on address 172.x.x.x because of Read timed out.
[23:15:25 ERROR]: org.geysermc.platform.bungeecord.shaded.netty.handler.timeout.ReadTimeoutException
[23:15:25 INFO] [Geyser-BungeeCord]: Bedrock user with ip: /x.x.x.x has disconnected for reason CLOSED_BY_REMOTE_PEER
```
The haproxy is listening on `0.0.0.0:25565`, the Waterfall itself is listening on a private address `172.x.x.x:25577`.

```
remote:
  # The IP address of the remote (Java Edition) server
  address: 127.0.0.1
  # The port of the remote (Java Edition) server
  port: 25565
  # Authentication type. Can be offline, online, or floodgate (see https://github.com/GeyserMC/Geyser/wiki/Floodgate).
  auth-type: online
```
After changing the config to this, Geyser still uses 172.x.x.x:25577 as host.

**To Reproduce**

Change the `address` and `port` in `remote` selection in `config.yml`

**Expected behavior**

The host config of Geyser should follow the `config.yml`.

**Server Version**

`This server is running Waterfall version git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:8afc4e2:366 by md_5`

**Geyser Version**

`(git-master-3ef7e30) (Java: 1.16.1, Bedrock: 1.16.0)`

**Minecraft: Bedrock Edition Version**

1.16.0

### PR DESCRIPTION
**Pull request by R-Josef**
To deal with this problem #1110 , set default remote address setting to "auto". And if it is "auto", for standalone version the remote address will be set to 127.0.0.1, for plugin version the remote address will follow the server's listening address, the port will also follow the server's listening port.

### CODE REVIEW

File: bootstrap/standalone/src/main/java/org/geysermc/platform/standalone/GeyserStandaloneBootstrap.java [hunk 1]
```diff
@@ -108,6 +108,9 @@ public void onEnable() {
         try {
             File configFile = FileUtils.fileOrCopiedFromResource("config.yml", (x) -> x.replaceAll("generateduuid", UUID.randomUUID().toString()));
             geyserConfig = FileUtils.loadConfig(configFile, GeyserStandaloneConfiguration.class);
+            if (this.geyserConfig.getRemote().getAddress().equalsIgnoreCase("auto")) {
+            	geyserConfig.getRemote().setAddress("127.0.0.1");
```
Comment (DoctorMacc) [inline bootstrap/standalone/src/main/java/org/geysermc/platform/standalone/GeyserStandaloneBootstrap.java:112]: Indentation here looks off?

**Comment by DoctorMacc** [comment]
Thanks for the PR! The concept looks good; the only difference we should make is setting the remote address with `InetAddress.getLocalHost().getHostAddress()` (see #998). I may PR my changes into this PR.

File: bootstrap/standalone/src/main/java/org/geysermc/platform/standalone/GeyserStandaloneBootstrap.java (hunk 1 above)
Comment (R-Josef) [reply bootstrap/standalone/src/main/java/org/geysermc/platform/standalone/GeyserStandaloneBootstrap.java]: That's my mistake, now i fixed it, thank you.

**Comment by DoctorMacc** [comment]
Are you on our Geyser Discord?

**Comment by WOo0W** [comment]
We just joined the Discord group, but we don't usually use it.

**Comment by DoctorMacc** [comment]
Thanks for joining, but as of this moment it's not needed since I decided on doing things differently. I PR'd some of my changes from #998 into your repository.
