### PR TITLE
Fix index out of bounds exception in BlockBreakHandler

### LINKED ISSUE #5819: ArrayIndexOutOfBoundsException in BlockBreakHandler after updating to build 929 9/13/2025: d56cc11
### Describe the bug

After updating to Geyser build 929 9/13/2025: d56cc11, the server console is repeatedly spammed with ArrayIndexOutOfBoundsException errors when handling PlayerAuthInputPacket. This didn’t occur on earlier builds.

### To Reproduce

1. Run Paper 1.21.8 with Geyser-Spigot [Build 929](https://geysermc.org/download/)
2. Connect a Bedrock client
3. Break/place blocks or perform normal player actions (auth input packets get processed)
4. Console starts logging the exceptions.

### Expected behaviour

No errors should appear in console when Bedrock players perform normal actions.

### Screenshots / Videos

```
[13:41:39 WARN] [Geyser-Spigot] Could not translate packet PlayerAuthInputPacket
java.lang.ArrayIndexOutOfBoundsException: Index 88 out of bounds for length 6
    at org.geysermc.geyser.session.cache.BlockBreakHandler.handleBlockBreakActions(BlockBreakHandler.java:179)
    at org.geysermc.geyser.session.cache.BlockBreakHandler.handlePlayerAuthInputPacket(BlockBreakHandler.java:156)
    at org.geysermc.geyser.translator.protocol.bedrock.entity.player.input.BedrockPlayerAuthInputTranslator.translate(BedrockPlayerAuthInputTranslator.java:73)
    at org.geysermc.geyser.translator.protocol.bedrock.entity.player.input.BedrockPlayerAuthInputTranslator.translate(BedrockPlayerAuthInputTranslator.java:62)
    at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:92)
    at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:72)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
    at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:1570)
```

### Server Version and Plugins

Paper 1.21.8
Geyser-Spigot Build 929 · 9/13/2025: d56cc11

### Geyser Dump

https://dump.geysermc.org/je3v0Ir9iHonWZIyWwEVWlKsMwE5gd51

### Geyser Version

Build 1387: Commit d56cc11 

### Minecraft: Bedrock Edition Device/Version

Microsoft PC/Mobile - v1.21.100

### Additional Context

1. This error started only after updating from the previous build to Build 929 · 9/13/2025: [d56cc11](https://github.com/GeyserMC/Geyser/commit/d56cc112349e613e7167af344f59cab1c504648f)
2. Bedrock players still seem able to play, but the console is heavily spammed.

### PR DESCRIPTION
**Pull request by eclipseisoffline**
This PR _should_ (hopefully) fix #5819, which (I think) occurs because of out of bounds values for the face of the currently mined block.

The `BlockBreakHandler` has been switched to use Geyser's own `Direction` class, which has received a new static helper method for safely extracting a `Direction` from an untrusted source. The method checks whether the extracted value is within the right bounds, and if it isn't, logs a warning and returns `DOWN`.

### CODE REVIEW

File: core/src/main/java/org/geysermc/geyser/level/physics/Direction.java [hunk 1]
```diff
@@ -74,4 +80,13 @@ public boolean isHorizontal() {
         }
         throw new IllegalStateException();
     }
+
+    public static <T> Direction getUntrusted(T source, ToIntFunction<T> idExtractor) {
+        int id = idExtractor.applyAsInt(source);
+        if (id < 0 || id >= VALUES.length) {
+            GeyserImpl.getInstance().getLogger().warning("Received invalid direction from " + source + " (ID was " + id + ")");
```
Comment (Camotoy) [inline core/src/main/java/org/geysermc/geyser/level/physics/Direction.java:87]: Would vanilla log here as an invalid direction?

**Comment by Camotoy** [comment]
If we're exposing `pistonValue` like this in multiple places, then it probably shouldn't be called `pistonValue` anymore.

**Review by onebeastchris — APPROVED** [review]
