### PR TITLE
Set default player head rarity

### LINKED ISSUE #5513: Universal Graves inventory shows up blank on Bedrock
### Describe the bug

[Universal Graves](https://github.com/Patbox/UniversalGraves/) is a [Polymer](https://github.com/Patbox/polymer)-based gravestone mod that supports vanilla clients.

However, it's broken running on the latest Geyser-ViaProxy dev version, due to a translation error with the rarity of one or more player heads in the inventory, used to display UI elements.

Interacting with the empty menu in any way has no effect. Attempting to place an item in the grave will place the item back in your inventory, with no effect.

https://mclo.gs/dQGgbfD

### To Reproduce

1. Load into a Java world (with the dev version of Geyser-ViaProxy and Universal Graves on it), from Bedrock Edition.
2. Die.
3. Open your grave.
4. It's empty!

### Expected behaviour

The grave menu should open and show its UI elements properly on Bedrock Edition, just like it does on Java Edition.

### Screenshots / Videos

Grave menu, in Bedrock Edition:
Image

The same grave menu in Java Edition:
Image

### Server Version and Plugins

This server is running Geyser version 2.7.0-b818 (git-master-b06f1ed) (Java: 1.21.5, Bedrock: 1.21.50 - 1.21.51 - 1.21.70)

Fabric 1.20.1, loader version 0.16.13 - `fabric-server-mc.1.21.1-loader.0.16.13-launcher.1.0.3.jar`
ViaProxy version 3.4.2-SNAPSHOT [[ci.viaversion.com](https://ci.viaversion.com/view/Platforms/job/ViaProxy/)] [[ViaProxy-3.4.2-SNAPSHOT.jar direct download](https://ci.viaversion.com/view/Platforms/job/ViaProxy/lastSuccessfulBuild/artifact/build/libs/ViaProxy-3.4.2-SNAPSHOT.jar)]

**All of these mods are serverside**, and do not require a modded Java client to join (other than JEI, which has given me some very minor issues so far, in testing).
It's mostly world-generation and tweak-related stuff, with some support for mods like TrashSlot and Where Is It.

```
[root@minecraft mods]# ls
 adorabuild-structures-2.10.1-fabric-1.21.3.jar          keepmysoiltilled-1.21.1-2.5.jar
 AdvancedBackups-fabric-1.21-3.7.1.jar                   kleeslabs-fabric-1.21.1-21.1.4.jar
 alternate-current-mc1.21-1.9.0.jar                      lithium-fabric-0.15.0+mc1.21.1.jar
 architectury-13.0.8-fabric.jar                          medieval_buildings-1.21-1.1.0-fabric.jar
 areas-1.21.1-6.1.jar                                    modernfix-fabric-5.21.0+mc1.21.1.jar
 balm-fabric-1.21.1-21.0.41.jar                          naturallychargedcreepers-1.21.1-3.6.jar
 betterspawnercontrol-1.21.1-4.7.jar                     netherportalfix-fabric-1.21.1-21.1.3.jar
 chorusfruitdropsnearby-1.21.1-1.1.jar                   noanimaltemptdelay-1.21.1-1.2.jar
 chunksending-fabric-1.21-2.8.jar                        NoChatReports-FABRIC-1.21.1-v2.9.1.jar
 Chunky-Fabric-1.4.23.jar                                nofeathertrample-1.21.1-1.3.jar
 clifftree-2.0.1.jar                                     polymer-bundled-0.9.18+1.21.1.jar
 cloth-config-15.0.140-fabric.jar                        quickrightclick-1.21.1-1.6.jar
 collective-1.21.1-8.3.jar                               recipecommands-1.21.1-3.6.jar
 compacthelpcommand-1.21.1-2.8.jar                       replantingcrops-1.21.1-5.5.jar
 conduitspreventdrowned-1.21.1-3.9.jar                   respawningshulkers-1.21.1-4.1.jar
 convenient-mobgriefing-2.1.2.jar                       'Revamped Shipwrecks 1.1.0.jar'
 cupboard-fabric-1.21-2.9.jar                            scaffoldingdropsnearby-1.21.1-3.4.jar
 cyclepaintings-1.21.1-4.1.jar                           shulkerdropstwo-1.21.1-3.5.jar
 dismountentity-1.21.1-3.6.jar                           skeletonhorsespawn-1.21.1-4.1.jar
'DnT-ancient-city-overhaul-v2 [Fabric].jar'              smoothchunk-fabric-1.21-4.1.jar
'DnT-end-castle-standalone-v1.1 [Fabric].jar'            spark-1.10.109-fabric.jar
'DnT-pillager-outpost-overhaul-v2.2 [Fabric].jar'        sparsestructures-fabric-1.21.1-3.0.jar
'DnT-stronghold-overhaul-v2.1.f [Fabric].jar'            StackDeobfuscatorFabric-1.4.3+08e71cc.jar
'DnT-woodland-mansion-replacement-v1.2 [Fabric].jar'     stackrefill-1.21.1-4.6.jar
 dragondropselytra-1.21.1-3.5.jar                        stickyenchantinglapis-1.21.1-1.5.jar
'dungeons-and-taverns-v4.4.4 [Fabric].jar'               Structory_1.21.x_v1.3.10.jar
 easyelevators-1.21.1-1.3.jar                            Structory_Towers_1.21.x_v1.0.11.jar
 easyelytratakeoff-1.21.1-4.5.jar                        structureessentials-fabric-1.21-4.7.jar
 emi-1.1.22+1.21.1+fabric.jar                            styled-chat-2.6.1+1.21.jar
'Explorify v1.6.2 f10-48.jar'                            styled-nicknames-1.6.0+1.21.jar
 fabric-api-0.115.6+1.21.1.jar                           supermartijn642configlib-1.1.8-fabric-mc1.21.jar
 fabric_medieval_buildings_end_edition-1.0.2-1.21.jar    Terralith_1.21.x_v2.5.8.jar
 ferritecore-7.0.2-hotfix-fabric.jar                     tidal-towns-1.3.4.jar
 firespreadtweaks-1.21.1-2.8.jar                         trashslot-fabric-1.21.1-21.1.4.jar
 Floodgate-Fabric-2.2.4-b38.jar                          treeharvester-1.21.1-9.1.jar
 formations-1.0.2-fabric-mc1.21.jar                      universal_shops-1.7.1+1.21.jar
 formationsnether-1.0.5-mc1.21+.jar                      villagernames-1.21.1-8.2.jar
 formationsoverworld-1.0.4-mc1.21+.jar                   villagespawnpoint-1.21.1-4.6.jar
'Geophilic v3.4.1 f15-71.mod.jar'                        whereisit-2.6.3+1.21.1.jar
 globalpacks-fabric-1.21-21.0.0.jar                      yet_another_config_lib_v3-3.6.6+1.21.1-fabric.jar
 grassseeds-1.21.1-3.4.jar                               YungsApi-1.21.1-Fabric-5.1.4.jar
 graves-3.4.4+1.21.jar                                   YungsBetterDesertTemples-1.21.1-Fabric-4.1.5.jar
 grieflogger-1.2.5-1.21.1-fabric.jar                     YungsBetterDungeons-1.21.1-Fabric-5.1.4.jar
'Hearths v1.0.3 f12-71.jar'                              YungsBetterEndIsland-1.21.1-Fabric-3.1.2.jar
 hideexperimentalwarning-1.21.1-1.2.jar                  YungsBetterJungleTemples-1.21.1-Fabric-3.1.2.jar
 hoetweaks-1.21.1-3.6.jar                                YungsBetterMineshafts-1.21.1-Fabric-5.1.1.jar
'HopoBetterMineshaft-[1.21-1.21.3]-1.3.0b.jar'           YungsBetterNetherFortresses-1.21.1-Fabric-3.1.4.jar
'HopoBetterRuinedPortals-[1.21.1-1.21.3]-1.4.4b.jar'     YungsBetterOceanMonuments-1.21.1-Fabric-4.1.2.jar
'HopoBetterUnderwaterRuins-[1.21.1-1.21.3]-1.2.1b.jar'   YungsBetterWitchHuts-1.21.1-Fabric-4.1.1.jar
 ImmediatelyFast-Fabric-1.6.5+1.21.1.jar                 YungsBridges-1.21.1-Fabric-5.1.1.jar
 ImprovedPillagerOutpost-v5.jar                          YungsExtras-1.21.1-Fabric-5.1.1.jar
 jei-1.21.1-fabric-19.21.0.247.jar                       zombiehorsespawn-1.21.1-5.2.jar
 justplayerheads-1.21.1-4.2.jar                          zombieproofdoors-1.21.1-3.5.jar
```

```
[root@minecraft] ls global_packs/required_data/
'bat membranes v1.0.12 (MC 1.21-1.21.5).zip'
'dragon drops v1.3.11 (MC 1.21-1.21.5).zip'
'ender chest always drops v1.0.3 (MC 1.21-1.21.5).zip'
'glass always drops v1.0.3 (MC 1.21-1.21.5).zip'
'more effective tools v1.0.5 (MC 1.21-1.21.5).zip'
 Remove_Terralith_Intro_Message_v1.1.zip
'spectator conduit power v1.1.11 (MC 1.21-1.21.5).zip'
'spectator night vision v1.1.11 (MC 1.21-1.21.5).zip'
'track raw statistics v1.7.7 (MC 1.21-1.21.5).zip'
'unlock all recipes v2.0.12 (MC 1.21-1.21.5).zip'
 VanillaTweaksCrafting.zip
```

### Geyser Dump

https://dump.geysermc.org/vuMxNvlAeQdCVTwYITfIGERIVx34RlrG

### Geyser Version

Geyser version 2.7.0-b818 (git-master-b06f1ed)

### Minecraft: Bedrock Edition Device/Version

1.21.72, iPhone

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rtm516**
Defaults player heads to common rarity in the case the component is missing. This prevents inventories from disappearing that contain an invalid head like this.

Fixes #5513

### CODE REVIEW

**Review by Camotoy — APPROVED** [review]

File: core/src/main/java/org/geysermc/geyser/item/type/PlayerHeadItem.java [hunk 1]
```diff
@@ -46,8 +46,14 @@ public PlayerHeadItem(Builder builder, Block block, Block... otherBlocks) {
...
 
+        // Get the rarity of the item or default to uncommon
+        Integer id = components.get(DataComponentTypes.RARITY);
+        if (id == null) {
+            id = Rarity.UNCOMMON.ordinal();
+        }
+
         // Use the correct color, determined by the rarity of the item
-        char rarity = Rarity.fromId(components.get(DataComponentTypes.RARITY)).getColor();
+        char rarity = Rarity.fromId(id).getColor();
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/item/type/PlayerHeadItem.java:56]: thoughts about using `getOrDefault` here instead?

Further, it might be worth it to test what would happen with the following player head:
`/give @a player_head[!rarity,profile={name:"jeb_"}] 1`
Which rarity would vanilla fall back to here?

Comment (rtm516) [reply core/src/main/java/org/geysermc/geyser/item/type/PlayerHeadItem.java:56]: Looks like it falls back to common so I've changed the default to match that

**Comment by Treeways** [comment]
Tested on ViaProxy; works great. Thank you!
