### PR TITLE
Inventory Fixes

### LINKED ISSUE #205: Inventory bar get hidden
**Describe the bug**
Sometime player's inventory bar got hidden(Tested on win10 that players can select item using kwyboard) when they die once they can see the inventory bar

**To Reproduce**
1. Build a spigot server with ScreamingBedWar plugin
2. Select a team
3. See error
(Detail in video below)

**Expected behavior**
Inventory bar showing without player dying once

**Screenshots**
[Video](https://streamable.com/8zypm)

**Server version**
spigot latest

**Geyser version**
Inventory branch latest

**Bedrock version**
latest 1.14

### LINKED ISSUE #211: Chest GUI doesn't work properly with menu plugins
**Describe the bug**
If a player misoperated/drag the item out of chest menu provided by a menu plugin, the item will drop on the floor. And this can be an exploit, for the player can pick it up, and then sell it or use it for crafting.
Also the "right click" behavior can't be used, but this is not a big problem.

**To Reproduce**
1. Download one menu plugin (in my case: DeluxeMenu-1.12.0) and place it into `plugins` folder.
2. Start server and on a mobile client, type `/examplemenu` to bring up the example menu.
3. Swap 2 items in the chest, for example: click the "**teltport to spawn**" item and swap it with the "**teleport home**" item, a dirt block will be dropped, go and pick it up, you will get a "**teleport to spawn**" dirt block.
4. Open inventory and double click on any dirt block, the lore on "**teleport to spawn**" block disappears, with `EssentialsX` installed, I can sell it by using the `/sell` command.
5. No error messages in the console log.

**Expected behavior**
Nothing drop out of the chest or the "touch" event is passed as "left click" event, so the chest closes fast enough and players won't get items out of the chest.

**Screenshots**
Later.

**Server version**
```
> version
[21:02:10 INFO]: This server is running Paper version git-Paper-134 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[21:02:10 INFO]: Checking version, please wait...
[21:02:14 INFO]: You are 2 version(s) behind
```

**Geyser version**
Using [#8 bukkit build](https://ci.nukkitx.com/job/Geyser/job/inventory/8/artifact/bootstrap/bukkit/target/Geyser-Bukkit.jar) in `inventory` branch.

**Bedrock version**
1.14.30.2 Android xbox version, not the original one.

**Additional context**
1. The right way to do a "left click" menu operation is to select an item and place it to a empty place.
2. If you change the menu command to something like `[player] say hello` or `[player] time set day` and follow the right operation, you will see the commands are actually getting runned on server, so I guess the menu part and the message communicate part is working correctly.
3. If you try to put something into the chest using simillar swap mechanics, the item will stay there when there is no "update item" in menu items, which is very funny, and the item will still last even if you drop out and login again...
4. Lore on the item disappears during select all same items is another problem, if one player tagged his item and did a "select all" action by accident, the lore will disappear.
5. If the chest interact thing are hard to deal with, maybe we can get through the lore disappear thing first, so OPs can restrict players from selling lored items. But the item can still be used for crafting, which is another problem 🤔

### PR DESCRIPTION
**Pull request by AJ-Ferguson**
Testing wanted to confirm the fixes are stable.
Should fix #211 and fix #205

### CODE REVIEW

**Comment by LegacyGamerHD** [comment]
@AJ-Ferguson  yes this fixes #211 heck yeah

File: connector/src/main/java/org/geysermc/connector/utils/InventoryUtils.java [hunk 1]
```diff
@@ -68,19 +69,34 @@ public static void openInventory(GeyserSession session, Inventory inventory) {
...
+
+    public static void closeWindow(GeyserSession session, int windowId) {
+        //Spamming close window packets can bug the client
+        if (System.currentTimeMillis() - session.getLastWindowCloseTime() > 500) {
+            ContainerClosePacket closePacket = new ContainerClosePacket();
+            closePacket.setWindowId((byte) windowId);
+            session.sendUpstreamPacket(closePacket);
+            session.setLastWindowCloseTime(System.currentTimeMillis());
+        }
     }
```
Comment (rtm516) [inline connector/src/main/java/org/geysermc/connector/utils/InventoryUtils.java:100]: Instead of discarding them, would it not be better just delaying them? (assuming there a different window id) Something like this is how other parts of Geyser do it.
```
session.getConnector().getGeneralThreadPool().schedule(() -> session.getEntityCache().spawnEntity(entity), 100, TimeUnit.MILLISECONDS)
```

**Comment by towuk118** [comment]
@RednedEpic , I build this fork and it worked, everything is fine, but double-check the code so that there is no garbage or errors in further work ❤

**Comment by DoctorMacc** [comment]
Is this PR ready for merge?

**Comment by AJ-Ferguson** [comment]
Yes
