### PR TITLE
Refactor the collision system, various improvements to how collision fixes is handle, more fixes (again).

### LINKED ISSUE #2819: Bedrock players are able to go through doors even if the event cancelled.
### Describe the bug

Bedrock players can go through doors or trapdoors, even if a plugin has canceled the event. Plugins like GriefPrevention, and LWCX have broken door protection because of it. 

### To Reproduce

1. Run a Paper server with GeyserMC, and any form of protection plugin (what I used was LWCX and GriefDefender).
2. Build an enclosure with only a single door as it's entrance.
3. Lock/Claim said entrance using a protection plugin.
4. Using a bedrock account, stand in front of the door and repeatedly open the door while holding the forward button.
5. For Java players, the door does not open at all. But, the player goes through the door.

### Expected behaviour

The player should not be able to go through the door.

### Screenshots / Videos

[Video](https://cdn.discordapp.com/attachments/613168464634576897/940477712718499850/Jdk17.0.1_12_2022.02.08_-_12.09.02.03.mp4)

### Server Version and Plugins

- Geyser; `This server is running Geyser version 2.0.0-SNAPSHOT (git-master-9d908c5) (Java: 1.18 - 1.18.1, Bedrock: 1.17.30 - 1.18.0/1.18.1/1.18.2)`
- Paper: `This server is running Paper version git-Paper-187 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0cc2503)`

### Geyser Dump

https://dump.geysermc.org/m0xiMh13GOr1AqPUqeRYEnjkLQky8Bg5

### Geyser Version

2.0.0-SNAPSHOT (git-master-9d908c5)

### Minecraft: Bedrock Edition Version

1.18.2

### Additional Context

_No response_

### LINKED ISSUE #4955: Damage with flooded chests
### Describe the bug

I fall on a flooded chest and take damage

### To Reproduce

we fall (height is more than 3 blocks) onto a chest (flooded with water) and take damage

### Expected behaviour

I fall on a flooded chest and take no damage

### Screenshots / Videos

_No response_

### Server Version and Plugins

_No response_

### Geyser Dump

_No response_

### Geyser Version

Newest

### Minecraft: Bedrock Edition Device/Version

1.21.2 Redmi 9A

### Additional Context

_No response_

### LINKED ISSUE #5930: When you close it so it overlaps the door, even if you try to go outside, you'll be pulled back inside.
### Describe the bug

https://github.com/user-attachments/assets/5170fdfa-31d2-4b08-8ebf-8d36441201ae

### To Reproduce

As shown in the video.
Note that rollbacks do not occur in Creative mode.

### Expected behaviour

Like in Java Edition or vanilla Minecraft Bedrock Edition, it can be buried in doors, And, no rollback occurs.

### Screenshots / Videos

_No response_

### Server Version and Plugins

Server version:
Paper version 1.21.8-56-main@65641d1 (2025-08-29T20:44:17Z) (Implementing API version 1.21.8-R0.1-SNAPSHOT)

Plugin:
floodgate, Geyser-Spigot, Multiverse-Core, UpOnlyKB, ViaBackwards, ViaVersion

### Geyser Dump

https://dump.geysermc.org/YHozTGBx6IglXha1LdCQONtoUHs1Toha

### Geyser Version

Geyser バージョン 2.9.0-b963 (git-master-b8a3c6d) (Java: 1.21.9、Bedrock: 1.21.90 - 1.21.114)

### Minecraft: Bedrock Edition Device/Version

1.21.114 Windows

### Additional Context

UpOnlyKB plugin is a simple my plugin that only grants upward velocity when taking damage.

### PR DESCRIPTION
**Pull request by oryxel1**
This is my second attempt, since I screw up the last one :) yay! so.

Changes:
- Deleted grass path collision fix since as of 1.21.71, this block collision is the same as java edition.
- Deleted the logic for stepping in `correctPosition`, since this caused many issues (already discuss in Discord).
- Refactor code inside `correctPosition`, make it little bit more readable.
- `correctPosition` now no longer return true/false, as in the original code this method always return true.
- Now for collisions fixes like trapdoor/door/glass pane/iron bar. Properly calculate the distance we actually need to move player position by instead of just moving it by a certain value, as the player could actually just clip less than that value, causing the position get offset more than it needed to, resolve #5930
- Fixed chest collision by moving player position down, resolve: #3277 and resolve #4955
- Fixed setback when hitting your head to an lantern
- Fixed setback when moving into an scaffolding due to collision differences (can be shown in #5787, however the player will fall through the scaffolding unlike java where they can walk on it (bedrock behaviour)).
- Also fixed some other small issues caused by my last PR.

Edit: resolve #2819, according to someone on discord :P

### CODE REVIEW

**Comment by onebeastchris** [comment]
I wonder if the collision fix for trap doors fixes https://github.com/GeyserMC/Geyser/issues/2951?

Let me know once this is ready for review & I'll do testing on my end

**Comment by oryxel1** [comment]
> I wonder if the collision fix for trap doors fixes #2951?

Nope it won't since as of now we're doing `Don't correct position if controlling a vehicle`, some changes have to made on the PR if we wanted to fix that.

Edit: Can't reproducible as of latest also.

**Comment by oryxel1** [comment]
I don't know what else to check for and add so I guess this PR is ready for review.

File: core/src/main/java/org/geysermc/geyser/translator/collision/fixes/ChestCollision.java [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+        super(boxes);
+    }
+
+    @Override
+    public void correctPosition(GeyserSession session, int x, int y, int z, BoundingBox playerCollision) {
+        super.correctPosition(session, x, y, z, playerCollision);
+
+        final SessionPlayerEntity player = session.getPlayerEntity();
+
+        // Player haven't even fall on the blocks yet, no need to move them down.
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/translator/collision/fixes/ChestCollision.java]:
```suggestion
        // Player didn't fall on the blocks yet, no need to move them down.
```

File: core/src/main/java/org/geysermc/geyser/translator/collision/fixes/ChestCollision.java [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+        if (!player.isCollidingVertically()) {
+            return;
+        }
+
+        final double collisionExpansion = CollisionManager.COLLISION_TOLERANCE * 2;
+        // Slightly expand the collision so we can see if the player is actually colliding with the block or not.
+        playerCollision.setSizeY(playerCollision.getSizeY() + collisionExpansion);
+
+        double beforeYVelocity = player.getLastTickEndVelocity().getY();
+        // If the player is already colliding with the block or player velocity y is larger than 0 then player likely don't need to be correct.
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/translator/collision/fixes/ChestCollision.java]:
```suggestion
        // If the player is already colliding with the block or player velocity y is larger than 0, then the player likely does not need a correction
```

File: core/src/main/java/org/geysermc/geyser/translator/collision/fixes/SeaPickleCollision.java [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+@EqualsAndHashCode(callSuper = true)
+@CollisionRemapper(regex = "^sea_pickle$", passDefaultBoxes = true)
+public class SeaPickleCollision extends BlockCollision {
+    public SeaPickleCollision(BlockState state, BoundingBox[] boxes) {
+        super(boxes);
+    }
+
+    @Override
+    protected void correctPosition(GeyserSession session, int x, int y, int z, BoundingBox blockCollision, BoundingBox playerCollision) {
+        // Check for sea pickle bug (sea pickle have no collision on Bedrock but does on Java).
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/translator/collision/fixes/SeaPickleCollision.java]:
```suggestion
        // Sea pickles have no collision on Bedrock but do on Java).
```

File: core/src/main/java/org/geysermc/geyser/translator/collision/fixes/ScaffoldingCollision.java [hunk 4]
```diff
@@ -51,6 +60,17 @@ public boolean correctPosition(GeyserSession session, int x, int y, int z, Bound
         playerCollision.setSizeY(playerCollision.getSizeY() + 0.001);
         playerCollision.setMiddleY(playerCollision.getMiddleY() - 0.002);
 
+        boolean canStandOn = playerCollision.getMin(Axis.Y) >= y + 1 && !session.isSneaking();
+
+        // If these condition are met, then the scaffolding will have a bottom collision that is 0.125 block height.
+        // However, this is not the case in Bedrock, so we push the player up by 0.125 blocks so player won't get setback.
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/translator/collision/fixes/ScaffoldingCollision.java]:
```suggestion
        // If these condition are met, then the scaffolding will have a bottom collision that is 0.125 block high.
        // However, this is not the case in Bedrock, so we push the player up by 0.125 blocks so the player won't get setback.
```

File: core/src/main/java/org/geysermc/geyser/translator/collision/fixes/ScaffoldingCollision.java [hunk 5]
```diff
@@ -51,6 +60,17 @@ public boolean correctPosition(GeyserSession session, int x, int y, int z, Bound
...
+        if (!canStandOn && this.bottom && playerCollision.getMin(Axis.Y) >= y) {
+            double distance = y + 0.125 - (playerCollision.getMin(Axis.Y)) ;
```
Comment (onebeastchris) [inline core/src/main/java/org/geysermc/geyser/translator/collision/fixes/ScaffoldingCollision.java]:
```suggestion
            double distance = y + 0.125 - (playerCollision.getMin(Axis.Y));
```
