### PR TITLE
Fix reading enchantments from server

### LINKED ISSUE #4834: Bedrock user can't read efficiency vanilla enchants and use the applied items.
### Describe the bug

Before this bug happen, i add GeyserOptionalPack into the server and ValhallaMMO RP into geyser pack. After that, bedrock user can't read enchantment on their items nor do they can use that items. And then our velocity panel throws error whenever bedrock user joined the server.

Log error when bedrock join : https://mclo.gs/3ZxuqmS
Log error when bedrock holding enchant item: https://mclo.gs/VyLWteB

### To Reproduce

Player join the server
Velocity throw error logs
Player can't read enchantments description that contains "efficiency"
Player can't use item that contains "efficiency"

### Expected behaviour

Player can read ecnhantments description and can use item with enchantments

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/104059783/5bbbfe18-4d56-40d5-84ec-3a34ad2f1ccc

https://github.com/GeyserMC/Geyser/assets/104059783/d0ef8a03-c5ca-4724-9255-b4786bc6bb5a

https://github.com/GeyserMC/Geyser/assets/104059783/d579d37c-6a0e-4cab-9a3d-7ab6beb1dd11

### Server Version and Plugins

Paper version 1.21-46-master@2fa5e0e (2024-07-06T21:32:48Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
Server Plugins (43):
- Paper Plugins:
Minepacks
- Bukkit Plugins:
AdvancedEnchantments, BetterRTP, ChatColor2, Chunky, CrazyVouchers, DecentHolograms, DeluxeMenus, DeluxeTags, EnchantsSquared, Essentials, EssentialsSpawn, FarmControl, FastAsyncWorldEdit, GriefPrevention, GSit, ImageFrame, InteractiveChat, ItemEdit, LPC, LuckPerms, Matrix, Multiverse-Core, NBTAPI, PlaceholderAPI, PlayerPoints, ProtocolLib, Shopkeepers, SimplePets, SkinsRestorer, spark, TAB, ValhallaMMO, ValhallaRaces, ValhallaTrinkets, Vault, ViaBackwards, ViaVersion, voicechat, VoidGen, VotingPlugin, WildTools, WorldGuard

### Geyser Dump

https://dump.geysermc.org/Y1ZnaaekfBc8yo3FTmRSBitsoopJHxGb

### Geyser Version

Geyser version 2.4.0-b593 (git-master-cbd59de) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.0/1.20.1)

### Minecraft: Bedrock Edition Device/Version

1.21 Minecraft Android

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by eclipseisoffline**
This PR implements proper reading of data driven enchantments from the server. As of right now, Geyser assumes the `supported_items` and `exclusive_set` tags in enchantments are item and enchantment tags respectively - but this isn't always the case. These tags are holder sets, and can therefore be an item/enchantment ID, an item/enchantment tag, or a list of item/enchantment IDs. This PR properly accommodates for this when reading enchantments.

The PR required a change to how registries are read in `RegistryCache`. A mapper method has been added that maps resource locations of a registry that's being read to their network IDs.

This PR *should* fix #4834, but I haven't tested it in their exact environment. I have created a simple datapack that reproduces the bug, available [here](https://github.com/user-attachments/files/16127214/geyser_bug.zip), which I have tested this fix with.

Additionally, the PR also slightly cleans up the read methods for data-driven registries, by using a simple new `RegistryEntryContext` record object (containing the Geyser session, the registry entry and more) instead of passing these as multiple arguments.

### CODE REVIEW

**Review by Konicai — COMMENTED** [review]
Can we keep the original `register` method and just have it delegate to the new one? That way the other registrations can stay at their visual complexity.

I also wouldn't be opposed to adding custom extensions of TriFunction/Function to reduce the type bulk. Just an idea, not sure what you or others think

File: core/src/main/java/org/geysermc/geyser/session/cache/RegistryCache.java [hunk 1]
```diff
@@ -149,25 +149,31 @@ public void load(ClientboundRegistryDataPacket packet) {
...
-        REGISTRIES.put(key, (registryCache, entries) -> {
+    private static <T> void register(String registry, Function<RegistryCache, JavaRegistry<T>> localCacheFunction, TriFunction<GeyserSession, Function<Key, Integer>, RegistryEntry, T> reader) {
+        Key registryKey = MinecraftKey.key(registry);
+        REGISTRIES.put(registryKey, (registryCache, entries) -> {
             Map<Key, NbtMap> localRegistry = null;
             JavaRegistry<T> localCache = localCacheFunction.apply(registryCache);
             // Clear each local cache every time a new registry entry is given to us
             // (e.g. proxy server switches)
+
+            Map<Key, Integer> entryIdMap = new HashMap<>();
```
Comment (Konicai) [inline core/src/main/java/org/geysermc/geyser/session/cache/RegistryCache.java:160]: Just add a brief comment about this being for readers that have to look back into the registry (enchants)

File: core/src/main/java/org/geysermc/geyser/inventory/recipe/TrimRecipe.java [hunk 2]
```diff
@@ -46,18 +45,18 @@ public final class TrimRecipe {
     public static final ItemDescriptorWithCount ADDITION = tagDescriptor("minecraft:trim_materials");
     public static final ItemDescriptorWithCount TEMPLATE = tagDescriptor("minecraft:trim_templates");
 
-    public static TrimMaterial readTrimMaterial(GeyserSession session, RegistryEntry entry) {
-        String key = entry.getId().asMinimalString();
+    public static TrimMaterial readTrimMaterial(RegistryContext context) {
```
Comment (Konicai) [inline core/src/main/java/org/geysermc/geyser/inventory/recipe/TrimRecipe.java:48]: nitpick, but, i would either keep these param names as `entry`, or add javadoc to RegistryContext that it is specific to the entry it contains (and is not a context for the whole registry)

Comment (eclipseisoffline) [reply core/src/main/java/org/geysermc/geyser/inventory/recipe/TrimRecipe.java:48]: I added a simple Javadoc to the RegistryContext record

**Comment by eclipseisoffline** [comment]
Renamed `RegistryContext` to `RegistryEntryContext` to make it clearer what it stores. If anyone disagrees I'll change it back, otherwise this PR is ready to be merged.

**Review by onebeastchris — APPROVED** [review]
Looks good to me :)

**Review by Konicai — APPROVED** [review]

File: core/src/main/java/org/geysermc/geyser/session/cache/RegistryCache.java [hunk 3]
```diff
@@ -149,25 +149,35 @@ public void load(ClientboundRegistryDataPacket packet) {
...
+        Key registryKey = MinecraftKey.key(registry);
+        REGISTRIES.put(registryKey, (registryCache, entries) -> {
             Map<Key, NbtMap> localRegistry = null;
             JavaRegistry<T> localCache = localCacheFunction.apply(registryCache);
             // Clear each local cache every time a new registry entry is given to us
             // (e.g. proxy server switches)
+
+            // Store each of the entries resource location IDs and their respective network ID,
+            // used for the key mapper that's currently only used by the Enchantment class
+            Map<Key, Integer> entryIdMap = new HashMap<>();
```
Comment (Camotoy) [inline core/src/main/java/org/geysermc/geyser/session/cache/RegistryCache.java:162]: This can be a Object2IntMap.

Comment (Camotoy) [reply core/src/main/java/org/geysermc/geyser/session/cache/RegistryCache.java:162]: Seems a bit wasteful to run this when it's rarely used, but for now it's fine. We can come back to it and lazily initialize it.

**Review by Camotoy — APPROVED** [review]
